CREATE POLICY oferta_materiale_select ON public.oferta_materiale AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY oferta_materiale_write ON public.oferta_materiale AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.oferta_materiale TO anon;
CREATE POLICY brokeri_all ON public.ofertare_brokeri AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_brokeri TO anon;
CREATE POLICY cal_all ON public.ofertare_calibrari AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_calibrari TO anon;
CREATE POLICY ocs_del ON public.ofertare_calibrari_subcontractori AS PERMISSIVE FOR DELETE TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY ocs_ins ON public.ofertare_calibrari_subcontractori AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY ocs_sel ON public.ofertare_calibrari_subcontractori AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY ocs_upd ON public.ofertare_calibrari_subcontractori AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_calibrari_subcontractori TO anon;
CREATE POLICY p_categorii_reguli_citire ON public.ofertare_categorii_reguli AS PERMISSIVE FOR SELECT TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY p_categorii_reguli_scriere ON public.ofertare_categorii_reguli AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_categorii_reguli TO anon;
CREATE POLICY ofertare_experienta_del ON public.ofertare_experienta AS PERMISSIVE FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY ofertare_experienta_ins ON public.ofertare_experienta AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY ofertare_experienta_sel ON public.ofertare_experienta AS PERMISSIVE FOR SELECT TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY ofertare_experienta_upd ON public.ofertare_experienta AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_experienta TO anon;
CREATE POLICY norm_all ON public.ofertare_normative AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_normative TO anon;
CREATE POLICY onp_read ON public.ofertare_norme_productivitate AS PERMISSIVE FOR SELECT TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY onp_write ON public.ofertare_norme_productivitate AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_norme_productivitate TO anon;
CREATE POLICY ofd_select ON public.ofertare_oferte_deschidere AS PERMISSIVE FOR SELECT TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY ofd_write ON public.ofertare_oferte_deschidere AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_oferte_deschidere TO anon;
CREATE POLICY oof_del ON public.ofertare_oferte_furnizori AS PERMISSIVE FOR DELETE TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY oof_ins ON public.ofertare_oferte_furnizori AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY oof_sel ON public.ofertare_oferte_furnizori AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY oof_upd ON public.ofertare_oferte_furnizori AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_oferte_furnizori TO anon;
CREATE POLICY ofertare_parteneri_all ON public.ofertare_parteneri AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_parteneri TO anon;
CREATE POLICY pm_all ON public.ofertare_preturi_materiale AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_preturi_materiale TO anon;
CREATE POLICY pu_all ON public.ofertare_preturi_unitare AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_preturi_unitare TO anon;
CREATE POLICY radar_del ON public.ofertare_radar AS PERMISSIVE FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY radar_ins ON public.ofertare_radar AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY radar_sel ON public.ofertare_radar AS PERMISSIVE FOR SELECT TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY radar_upd ON public.ofertare_radar AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_radar TO anon;
CREATE POLICY rfq_all ON public.ofertare_rfq AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_rfq TO anon;
CREATE POLICY rfqd_all ON public.ofertare_rfq_destinatari AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_rfq_destinatari TO anon;
CREATE POLICY rfqm_all ON public.ofertare_rfq_materiale AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_rfq_materiale TO anon;
CREATE POLICY rfqo_all ON public.ofertare_rfq_oferte AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_rfq_oferte TO anon;
CREATE POLICY rfqp_all ON public.ofertare_rfq_preturi AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.ofertare_rfq_preturi TO anon;
CREATE POLICY pof_select ON public.probe_oferte AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY pof_write ON public.probe_oferte AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
GRANT ALL ON TABLE public.probe_oferte TO anon;
