-- Fixture LOCAL pentru scripts/test_sec_f1b_maintain.sh: reproduce lista LIVE (01.10.2026) a relațiilor din public
-- cu MAINTAIN pentru anon/authenticated (477; amprenta 41e9610b39f6609d9f34a21d302360d2) + câteva fără. NU e migrare.
DO $r$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN CREATE ROLE service_role NOLOGIN; END IF;
END $r$;
-- setarea implicită a lui postgres pe public = cea live după F1: arwdxtm (fără D, cu m)
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE TRUNCATE ON TABLES FROM anon, authenticated;
CREATE TABLE public._backup_acoperire_racari_20260921 (id integer);
CREATE TABLE public._backup_clar63_20260927 (id integer);
CREATE TABLE public._dedup_racari_20260911 (id integer);
CREATE TABLE public._eval_candidati_inainte_20260921 (id integer);
CREATE TABLE public._eval_runda1_20260921 (id integer);
CREATE TABLE public._eval_runda2_20260921 (id integer);
CREATE TABLE public.ai_dezbateri (id integer);
CREATE TABLE public.ai_dezbateri_mesaje (id integer);
CREATE TABLE public.ai_documente_inbox (id integer);
CREATE TABLE public.ai_feedback (id integer);
CREATE TABLE public.ai_usage_log (id integer);
CREATE TABLE public.app_modules (id integer);
CREATE TABLE public.avize_cjp (id integer);
CREATE TABLE public.avize_serii_counter (id integer);
CREATE TABLE public.beneficiari (id integer);
CREATE TABLE public.calendar_days (id integer);
CREATE TABLE public.chat_members (id integer);
CREATE TABLE public.chat_messages (id integer);
CREATE TABLE public.chatbot_conversations (id integer);
CREATE TABLE public.chatbot_easter_eggs (id integer);
CREATE TABLE public.chatbot_usage (id integer);
CREATE TABLE public.claude_bot_runs (id integer);
CREATE TABLE public.claude_bot_silentiate (id integer);
CREATE TABLE public.claude_bot_sugestii (id integer);
CREATE TABLE public.claude_context (id integer);
CREATE TABLE public.claude_docs (id integer);
CREATE TABLE public.comanda_linii (id integer);
CREATE TABLE public.comenzi (id integer);
CREATE TABLE public.comenzi_aprobatori (id integer);
CREATE TABLE public.comenzi_documente (id integer);
CREATE TABLE public.comenzi_furnizor (id integer);
CREATE TABLE public.comenzi_furnizor_aprobari (id integer);
CREATE TABLE public.comenzi_furnizor_counter (id integer);
CREATE TABLE public.comenzi_furnizor_documente (id integer);
CREATE TABLE public.comenzi_furnizor_linii (id integer);
CREATE TABLE public.consumuri_proiect (id integer);
CREATE TABLE public.consumuri_proiect_linii (id integer);
CREATE TABLE public.contab_expert_importuri (id integer);
CREATE TABLE public.contab_expert_linii (id integer);
CREATE TABLE public.contab_santier_map (id integer);
CREATE TABLE public.contracte_acte_aditionale (id integer);
CREATE TABLE public.contracte_linii (id integer);
CREATE TABLE public.contracte_polite (id integer);
CREATE TABLE public.contracte_polite_acte (id integer);
CREATE TABLE public.contracte_subcontract_facturi (id integer);
CREATE TABLE public.contracte_subcontract_import (id integer);
CREATE TABLE public.contracte_templates (id integer);
CREATE TABLE public.contracte_terti (id integer);
CREATE TABLE public.ctc_carti (id integer);
CREATE TABLE public.ctc_documente (id integer);
CREATE TABLE public.ctc_documente_carte (id integer);
CREATE TABLE public.ctc_template_pozitii (id integer);
CREATE TABLE public.ctc_templates (id integer);
CREATE TABLE public.diurna_payment_details (id integer);
CREATE TABLE public.diurna_payments (id integer);
CREATE TABLE public.documente_firma (id integer);
CREATE TABLE public.documente_proiect (id integer);
CREATE TABLE public.employee_salaries (id integer);
CREATE TABLE public.employees (id integer);
CREATE TABLE public.evogps_alias (id integer);
CREATE TABLE public.evogps_imports_log (id integer);
CREATE TABLE public.executie_acte_aditionale (id integer);
CREATE TABLE public.executie_alerte_ai (id integer);
CREATE TABLE public.executie_alocari_personal (id integer);
CREATE TABLE public.executie_bonuri_consum (id integer);
CREATE TABLE public.executie_bonuri_consum_linii (id integer);
CREATE TABLE public.executie_completari_propuse (id integer);
CREATE TABLE public.executie_documente_contract (id integer);
CREATE TABLE public.executie_documente_referinta (id integer);
CREATE TABLE public.executie_faze_determinante (id integer);
CREATE TABLE public.executie_ordine_detectate (id integer);
CREATE TABLE public.executie_ordine_sistare (id integer);
CREATE TABLE public.executie_pachete_cumulat_final (id integer);
CREATE TABLE public.executie_pachete_cumulat_tevi (id integer);
CREATE TABLE public.executie_pachete_documente (id integer);
CREATE TABLE public.executie_pachete_exports (id integer);
CREATE TABLE public.executie_pachete_lansare (id integer);
CREATE TABLE public.executie_pachete_sudura_sant (id integer);
CREATE TABLE public.executie_probe_presiune (id integer);
CREATE TABLE public.executie_proiecte (id integer);
CREATE TABLE public.executie_situatii_plata (id integer);
CREATE TABLE public.executie_situatii_plata_linii (id integer);
CREATE TABLE public.executie_sl_ajustari (id integer);
CREATE TABLE public.executie_tevi (id integer);
CREATE TABLE public.executie_tronsoane (id integer);
CREATE TABLE public.executie_tura_activitati (id integer);
CREATE TABLE public.executie_tura_naveta (id integer);
CREATE TABLE public.executie_tura_subcontractori (id integer);
CREATE TABLE public.executie_ture (id integer);
CREATE TABLE public.facturi_emise (id integer);
CREATE TABLE public.facturi_serii_counter (id integer);
CREATE TABLE public.firma_profil (id integer);
CREATE TABLE public.garantii (id integer);
CREATE TABLE public.garantii_alerte_amprenta (id integer);
CREATE TABLE public.gbe_polite (id integer);
CREATE TABLE public.gbe_restituiri (id integer);
CREATE TABLE public.grafic_activitati (id integer);
CREATE TABLE public.grafic_parametri (id integer);
CREATE TABLE public.grafic_versiuni (id integer);
CREATE TABLE public.hr_adeverinte_legator (id integer);
CREATE TABLE public.hr_aprobatori (id integer);
CREATE TABLE public.hr_autorizatii (id integer);
CREATE TABLE public.hr_autorizatii_propuneri (id integer);
CREATE TABLE public.hr_autorizatii_rsvti_confirmari (id integer);
CREATE TABLE public.hr_autorizatii_tipuri (id integer);
CREATE TABLE public.hr_cereri_concediu (id integer);
CREATE TABLE public.hr_ci_extrase (id integer);
CREATE TABLE public.hr_concediu_rute (id integer);
CREATE TABLE public.hr_concediu_tokens (id integer);
CREATE TABLE public.hr_documente_personale (id integer);
CREATE TABLE public.hr_documente_personale_tipuri (id integer);
CREATE TABLE public.hr_employees_audit (id integer);
CREATE TABLE public.hr_employees_private (id integer);
CREATE TABLE public.hr_formare_profesionala (id integer);
CREATE TABLE public.hr_personal_extern (id integer);
CREATE TABLE public.hr_recomandari (id integer);
CREATE TABLE public.hr_recrutare_candidati (id integer);
CREATE TABLE public.hr_recrutare_interactiuni (id integer);
CREATE VIEW public.hr_recrutare_oferte_trimise AS SELECT 1 AS id;
CREATE TABLE public.hr_recrutare_pozitii (id integer);
CREATE VIEW public.hr_recrutare_retentie_expirata AS SELECT 1 AS id;
CREATE TABLE public.hr_salarii_audit (id integer);
CREATE TABLE public.hr_semnaturi_electronice (id integer);
CREATE TABLE public.internal_chats (id integer);
CREATE TABLE public.iot_citiri (id integer);
CREATE TABLE public.iot_dispozitive (id integer);
CREATE TABLE public.iot_integrari (id integer);
CREATE TABLE public.iot_privat_acces (id integer);
CREATE TABLE public.isc_rte_domenii (id integer);
CREATE TABLE public.locatii_cheltuieli (id integer);
CREATE TABLE public.locatii_furnizori (id integer);
CREATE TABLE public.locatii_inchiriate (id integer);
CREATE TABLE public.logistica_achizitii_vrac (id integer);
CREATE TABLE public.logistica_active (id integer);
CREATE TABLE public.logistica_active_km_ore_ajustari (id integer);
CREATE TABLE public.logistica_active_poze (id integer);
CREATE TABLE public.logistica_alerte_consum (id integer);
CREATE TABLE public.logistica_alimentari (id integer);
CREATE TABLE public.logistica_alimentari_card (id integer);
CREATE TABLE public.logistica_alocari (id integer);
CREATE TABLE public.logistica_amc (id integer);
CREATE TABLE public.logistica_amc_tipuri (id integer);
CREATE TABLE public.logistica_audit_log (id integer);
CREATE TABLE public.logistica_avize_arhiva (id integer);
CREATE TABLE public.logistica_bonuri_carburant (id integer);
CREATE TABLE public.logistica_bonuri_comune (id integer);
CREATE TABLE public.logistica_categorii (id integer);
CREATE TABLE public.logistica_cesiuni_subcontractor (id integer);
CREATE TABLE public.logistica_comenzi_transport (id integer);
CREATE TABLE public.logistica_comenzi_transport_itemi (id integer);
CREATE TABLE public.logistica_costuri (id integer);
CREATE TABLE public.logistica_curse_gps (id integer);
CREATE TABLE public.logistica_declaratii (id integer);
CREATE TABLE public.logistica_depozite (id integer);
CREATE TABLE public.logistica_documente (id integer);
CREATE TABLE public.logistica_furnizori (id integer);
CREATE TABLE public.logistica_importuri_rompetrol (id integer);
CREATE TABLE public.logistica_imprumuturi (id integer);
CREATE TABLE public.logistica_mentenanta_istoric (id integer);
CREATE TABLE public.logistica_mentenanta_plan (id integer);
CREATE TABLE public.logistica_oscar_dispense (id integer);
CREATE TABLE public.logistica_piese_catalog (id integer);
CREATE TABLE public.logistica_piese_istoric (id integer);
CREATE TABLE public.logistica_piese_poze (id integer);
CREATE TABLE public.logistica_probleme (id integer);
CREATE TABLE public.logistica_probleme_jurnal (id integer);
CREATE TABLE public.logistica_qr_submit_log (id integer);
CREATE TABLE public.logistica_rezervoare (id integer);
CREATE TABLE public.logistica_service_fise (id integer);
CREATE TABLE public.logistica_service_fise_documente (id integer);
CREATE TABLE public.logistica_service_intrari (id integer);
CREATE TABLE public.logistica_service_itemi_preset (id integer);
CREATE TABLE public.logistica_service_parteneri (id integer);
CREATE TABLE public.logistica_setari (id integer);
CREATE TABLE public.logistica_subcontractori (id integer);
CREATE TABLE public.logistica_supape (id integer);
CREATE TABLE public.logistica_telemetrie_zilnica (id integer);
CREATE TABLE public.logistica_tipuri_documente (id integer);
CREATE TABLE public.logistica_transporturi (id integer);
CREATE TABLE public.logistica_transporturi_continut (id integer);
CREATE TABLE public.magazie_bucati (id integer);
CREATE TABLE public.magazie_echipamente (id integer);
CREATE TABLE public.magazie_inventar_angajat (id integer);
CREATE TABLE public.magazie_tipuri_material (id integer);
CREATE TABLE public.magazii (id integer);
CREATE TABLE public.mai_gov_redirect_log (id integer);
CREATE TABLE public.marketing_aprobatori (id integer);
CREATE TABLE public.marketing_postari (id integer);
CREATE TABLE public.marketing_santiere (id integer);
CREATE TABLE public.materiale (id integer);
CREATE TABLE public.meteo_cache (id integer);
CREATE TABLE public.module_noutati (id integer);
CREATE TABLE public.module_noutati_citiri (id integer);
CREATE TABLE public.nas_documente (id integer);
CREATE TABLE public.nas_proiecte (id integer);
CREATE TABLE public.necesar_articole (id integer);
CREATE TABLE public.necesar_linii (id integer);
CREATE TABLE public.necesar_notif_log (id integer);
CREATE TABLE public.necesar_responsabili (id integer);
CREATE TABLE public.necesar_runde (id integer);
CREATE TABLE public.necesar_setari (id integer);
CREATE TABLE public.notification_logs (id integer);
CREATE TABLE public.notification_templates (id integer);
CREATE TABLE public.notifications (id integer);
CREATE TABLE public.oferta_materiale (id integer);
CREATE TABLE public.ofertare_acoperire (id integer);
CREATE TABLE public.ofertare_acoperire_coada (id integer);
CREATE TABLE public.ofertare_acoperire_istoric (id integer);
CREATE TABLE public.ofertare_acoperire_revizii (id integer);
CREATE TABLE public.ofertare_alerte_amprenta (id integer);
CREATE TABLE public.ofertare_brokeri (id integer);
CREATE TABLE public.ofertare_calibrari (id integer);
CREATE TABLE public.ofertare_calibrari_subcontractori (id integer);
CREATE TABLE public.ofertare_cantitati (id integer);
CREATE TABLE public.ofertare_categorii_reguli (id integer);
CREATE TABLE public.ofertare_cerinte (id integer);
CREATE TABLE public.ofertare_cerinte_pozitii (id integer);
CREATE TABLE public.ofertare_citire_test (id integer);
CREATE TABLE public.ofertare_clarificari (id integer);
CREATE TABLE public.ofertare_clarificari_coada (id integer);
CREATE TABLE public.ofertare_clarificari_puncte (id integer);
CREATE TABLE public.ofertare_clauze_contract (id integer);
CREATE TABLE public.ofertare_documente_atribuire (id integer);
CREATE TABLE public.ofertare_experienta (id integer);
CREATE TABLE public.ofertare_extragere_coada (id integer);
CREATE TABLE public.ofertare_formulare_registru (id integer);
CREATE TABLE public.ofertare_garantii (id integer);
CREATE TABLE public.ofertare_ingest_coada (id integer);
CREATE TABLE public.ofertare_ingest_lansari (id integer);
CREATE TABLE public.ofertare_inventar_ai (id integer);
CREATE TABLE public.ofertare_licitatii (id integer);
CREATE TABLE public.ofertare_mailuri (id integer);
CREATE TABLE public.ofertare_nas_inventar (id integer);
CREATE TABLE public.ofertare_normative (id integer);
CREATE TABLE public.ofertare_norme_productivitate (id integer);
CREATE TABLE public.ofertare_oferte_deschidere (id integer);
CREATE TABLE public.ofertare_oferte_furnizori (id integer);
CREATE TABLE public.ofertare_organigrama (id integer);
CREATE TABLE public.ofertare_parteneri (id integer);
CREATE TABLE public.ofertare_parteneri_documente (id integer);
CREATE TABLE public.ofertare_participari (id integer);
CREATE TABLE public.ofertare_preturi_materiale (id integer);
CREATE TABLE public.ofertare_preturi_unitare (id integer);
CREATE TABLE public.ofertare_pt_afirmatii (id integer);
CREATE TABLE public.ofertare_pt_anexe_asteptate (id integer);
CREATE TABLE public.ofertare_pt_capitole (id integer);
CREATE TABLE public.ofertare_pt_capitole_versiuni (id integer);
CREATE TABLE public.ofertare_pt_declaratii (id integer);
CREATE TABLE public.ofertare_pt_dovezi (id integer);
CREATE TABLE public.ofertare_pt_echipa (id integer);
CREATE TABLE public.ofertare_pt_echipa_roluri (id integer);
CREATE TABLE public.ofertare_pt_garantie (id integer);
CREATE TABLE public.ofertare_pt_legaturi (id integer);
CREATE TABLE public.ofertare_pt_observatii (id integer);
CREATE TABLE public.ofertare_pt_pachet (id integer);
CREATE TABLE public.ofertare_pt_pachet_fisiere (id integer);
CREATE TABLE public.ofertare_pt_participanti (id integer);
CREATE TABLE public.ofertare_pt_poarta (id integer);
CREATE TABLE public.ofertare_radar (id integer);
CREATE TABLE public.ofertare_radar_scan_log (id integer);
CREATE TABLE public.ofertare_raport_zilnic (id integer);
CREATE TABLE public.ofertare_rfq (id integer);
CREATE TABLE public.ofertare_rfq_destinatari (id integer);
CREATE TABLE public.ofertare_rfq_materiale (id integer);
CREATE TABLE public.ofertare_rfq_oferte (id integer);
CREATE TABLE public.ofertare_rfq_preturi (id integer);
CREATE TABLE public.ofertare_seap_manifest (id integer);
CREATE TABLE public.ofertare_solicitari_ac (id integer);
CREATE TABLE public.ofertare_solicitari_ac_anexe (id integer);
CREATE TABLE public.ofertare_solicitari_ac_puncte (id integer);
CREATE TABLE public.ofertare_source_pack (id integer);
CREATE TABLE public.ofertare_source_pack_importuri (id integer);
CREATE TABLE public.ofertare_triere (id integer);
CREATE TABLE public.ofertare_verificari (id integer);
CREATE TABLE public.olx_atribute_seturi (id integer);
CREATE TABLE public.olx_categorii (id integer);
CREATE TABLE public.olx_mesaje_procesate (id integer);
CREATE TABLE public.olx_orase (id integer);
CREATE TABLE public.olx_tokens (id integer);
CREATE TABLE public.ordine_deplasare_arhiva (id integer);
CREATE TABLE public.organigrama_propuneri (id integer);
CREATE TABLE public.piese_import_staging (id integer);
CREATE TABLE public.platforma_noutati (id integer);
CREATE TABLE public.pontaj_brut_istoric (id integer);
CREATE TABLE public.pontaj_net_istoric (id integer);
CREATE TABLE public.pontaj_records (id integer);
CREATE TABLE public.probe_calcule (id integer);
CREATE TABLE public.probe_configuratii (id integer);
CREATE TABLE public.probe_diametre (id integer);
CREATE TABLE public.probe_log_executie (id integer);
CREATE TABLE public.probe_oferte (id integer);
CREATE TABLE public.probe_transport_tarife (id integer);
CREATE TABLE public.procese_heartbeat (id integer);
CREATE TABLE public.productie_documente (id integer);
CREATE TABLE public.productie_facturi (id integer);
CREATE TABLE public.productie_lot_componente (id integer);
CREATE TABLE public.productie_loturi (id integer);
CREATE TABLE public.productie_materiale (id integer);
CREATE TABLE public.productie_materiale_miscari (id integer);
CREATE TABLE public.productie_produse (id integer);
CREATE TABLE public.productie_serii (id integer);
CREATE TABLE public.productie_stoc_miscari (id integer);
CREATE TABLE public.profile_sites (id integer);
CREATE TABLE public.profiles (id integer);
CREATE TABLE public.proiect_activitate_coduri (id integer);
CREATE TABLE public.proiect_activitati (id integer);
CREATE TABLE public.proiect_articole (id integer);
CREATE TABLE public.proiect_unitati (id integer);
CREATE TABLE public.proiecte_ofertare (id integer);
CREATE TABLE public.rag_ingest_queue (id integer);
CREATE TABLE public.rag_normative (id integer);
CREATE TABLE public.rag_qr_log (id integer);
CREATE TABLE public.rag_utilaje (id integer);
CREATE TABLE public.rapoarte_zilnice (id integer);
CREATE VIEW public.raport_detaliat_financiar AS SELECT 1 AS id;
CREATE TABLE public.raport_lucrari (id integer);
CREATE TABLE public.registru_imobilizari (id integer);
CREATE TABLE public.reminder_rapoarte_log (id integer);
CREATE TABLE public.salarii_importuri (id integer);
CREATE TABLE public.salarii_stat_linii (id integer);
CREATE TABLE public.scanner_logs (id integer);
CREATE TABLE public.sedinte (id integer);
CREATE TABLE public.sedinte_invitati (id integer);
CREATE TABLE public.sedinte_linii (id integer);
CREATE TABLE public.sedinte_rsvp (id integer);
CREATE TABLE public.service_import_ai_log (id integer);
CREATE TABLE public.service_import_ai_mappings (id integer);
CREATE TABLE public.setari_ordin_deplasare (id integer);
CREATE TABLE public.setari_recycle_bin (id integer);
CREATE TABLE public.settings (id integer);
CREATE TABLE public.sites (id integer);
CREATE TABLE public.stocuri (id integer);
CREATE TABLE public.stocuri_miscari (id integer);
CREATE TABLE public.storage_rls_errors (id integer);
CREATE TABLE public.supliment_hrana_istoric (id integer);
CREATE TABLE public.talon_extract_staging (id integer);
CREATE TABLE public.tichete (id integer);
CREATE TABLE public.tichete_asignati (id integer);
CREATE TABLE public.tichete_comentarii (id integer);
CREATE TABLE public.tichete_default_responsabili (id integer);
CREATE TABLE public.tichete_istoric (id integer);
CREATE TABLE public.tichete_subcategorii (id integer);
CREATE TABLE public.transferuri_interne (id integer);
CREATE TABLE public.transferuri_linii (id integer);
CREATE TABLE public.trezorerie_conturi (id integer);
CREATE TABLE public.trezorerie_extras_linii (id integer);
CREATE TABLE public.upa_achizitii (id integer);
CREATE TABLE public.user_module_access (id integer);
CREATE VIEW public.v_acte_aditionale_toate AS SELECT 1 AS id;
CREATE VIEW public.v_active_date_lipsa AS SELECT 1 AS id;
CREATE VIEW public.v_active_disponibile AS SELECT 1 AS id;
CREATE VIEW public.v_active_fara_norma_cu_alimentari AS SELECT 1 AS id;
CREATE VIEW public.v_active_km_ore AS SELECT 1 AS id;
CREATE VIEW public.v_active_santier_recent AS SELECT 1 AS id;
CREATE VIEW public.v_activitate_hr_zilnica AS SELECT 1 AS id;
CREATE VIEW public.v_activitate_logistica_zilnica AS SELECT 1 AS id;
CREATE VIEW public.v_ai_cost_luna_curenta AS SELECT 1 AS id;
CREATE VIEW public.v_alerte_act_aditional AS SELECT 1 AS id;
CREATE VIEW public.v_alerte_contracte AS SELECT 1 AS id;
CREATE VIEW public.v_alim_fara_telemetrie AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_dubluri_oscar AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_fara_santier AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_kpi AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_ocr_revizuire AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_pt_ocr AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_suspecte AS SELECT 1 AS id;
CREATE VIEW public.v_alimentari_ultima AS SELECT 1 AS id;
CREATE VIEW public.v_audit_alimentari_gap AS SELECT 1 AS id;
CREATE VIEW public.v_audit_cesiuni_subcontractor AS SELECT 1 AS id;
CREATE VIEW public.v_audit_motorina_comodat AS SELECT 1 AS id;
CREATE VIEW public.v_audit_rompetrol_lunar AS SELECT 1 AS id;
CREATE VIEW public.v_audit_rompetrol_vehicule AS SELECT 1 AS id;
CREATE VIEW public.v_audit_split_anual AS SELECT 1 AS id;
CREATE VIEW public.v_audit_split_detail AS SELECT 1 AS id;
CREATE VIEW public.v_audit_split_lunar AS SELECT 1 AS id;
CREATE VIEW public.v_audit_split_trim AS SELECT 1 AS id;
CREATE VIEW public.v_bonuri_comune_status AS SELECT 1 AS id;
CREATE VIEW public.v_bonuri_consum_nepreluate AS SELECT 1 AS id;
CREATE VIEW public.v_card_swap_audit AS SELECT 1 AS id;
CREATE VIEW public.v_chat_list AS SELECT 1 AS id;
CREATE VIEW public.v_chatbot_usage_analytics AS SELECT 1 AS id;
CREATE VIEW public.v_chuck_hr_alerte AS SELECT 1 AS id;
CREATE VIEW public.v_chuck_hr_fara_aviz_medical AS SELECT 1 AS id;
CREATE VIEW public.v_citire_test_pagini AS SELECT 1 AS id;
CREATE VIEW public.v_claude_context_smart AS SELECT 1 AS id;
CREATE VIEW public.v_comodat_depasiri_lunare AS SELECT 1 AS id;
CREATE VIEW public.v_contract_efecte_acte AS SELECT 1 AS id;
CREATE VIEW public.v_contracte_cu_linii AS SELECT 1 AS id;
CREATE VIEW public.v_contracte_executat AS SELECT 1 AS id;
CREATE VIEW public.v_cost_total_per_activ_luna AS SELECT 1 AS id;
CREATE VIEW public.v_cross_check_km_alerte AS SELECT 1 AS id;
CREATE VIEW public.v_ctc_carti_progres AS SELECT 1 AS id;
CREATE VIEW public.v_declaratie_tehnica_status AS SELECT 1 AS id;
CREATE VIEW public.v_documente_firma_alerte AS SELECT 1 AS id;
CREATE VIEW public.v_dovezi_stare AS SELECT 1 AS id;
CREATE VIEW public.v_echipament_furnizor AS SELECT 1 AS id;
CREATE VIEW public.v_employee_work_hours AS SELECT 1 AS id;
CREATE VIEW public.v_executie_alerte_count AS SELECT 1 AS id;
CREATE VIEW public.v_executie_alocari AS SELECT 1 AS id;
CREATE VIEW public.v_executie_alocari_conflicte AS SELECT 1 AS id;
CREATE VIEW public.v_executie_dashboard AS SELECT 1 AS id;
CREATE VIEW public.v_executie_personal_site AS SELECT 1 AS id;
CREATE VIEW public.v_executie_sanatate AS SELECT 1 AS id;
CREATE VIEW public.v_furnizori_stats AS SELECT 1 AS id;
CREATE VIEW public.v_garantii_plafon_emitent AS SELECT 1 AS id;
CREATE VIEW public.v_garantii_situatie AS SELECT 1 AS id;
CREATE VIEW public.v_gbe_per_contract AS SELECT 1 AS id;
CREATE VIEW public.v_hr_adeverinte_legator_candidati AS SELECT 1 AS id;
CREATE VIEW public.v_hr_autorizatii_arhiva AS SELECT 1 AS id;
CREATE VIEW public.v_hr_autorizatii_status AS SELECT 1 AS id;
CREATE VIEW public.v_hr_calificare_peste_cim AS SELECT 1 AS id;
CREATE VIEW public.v_hr_date_lipsa AS SELECT 1 AS id;
CREATE VIEW public.v_hr_documente_personale_status AS SELECT 1 AS id;
CREATE VIEW public.v_hr_formare_cursuri AS SELECT 1 AS id;
CREATE VIEW public.v_hr_sold_co AS SELECT 1 AS id;
CREATE VIEW public.v_km_pompa_vs_evogps AS SELECT 1 AS id;
CREATE VIEW public.v_kpi_logistica AS SELECT 1 AS id;
CREATE VIEW public.v_locatii_sumar_lunar AS SELECT 1 AS id;
CREATE VIEW public.v_logistica_alerte AS SELECT 1 AS id;
CREATE VIEW public.v_logistica_alerte_globale AS SELECT 1 AS id;
CREATE VIEW public.v_logistica_piese_catalog_uz AS SELECT 1 AS id;
CREATE VIEW public.v_magazie_echipamente AS SELECT 1 AS id;
CREATE VIEW public.v_magazie_inventar_activ AS SELECT 1 AS id;
CREATE VIEW public.v_nas_documente_recente AS SELECT 1 AS id;
CREATE VIEW public.v_nas_statistici AS SELECT 1 AS id;
CREATE VIEW public.v_necesar_cumulat AS SELECT 1 AS id;
CREATE VIEW public.v_necesar_sumar_lunar AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_cerinte_dovezi AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_completitudine AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_contradictii AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_dashboard AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_dotari AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_identitate_tokens AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_pt_cerinte_neconfirmate AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_pt_conformitate AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_pt_echipa AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_pt_echipa_blocaje AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_pt_stare AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_pt_suprapuneri AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_seap_completitudine AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_solicitari_ac_stare AS SELECT 1 AS id;
CREATE VIEW public.v_olx_categorii AS SELECT 1 AS id;
CREATE VIEW public.v_ordine_lipsa AS SELECT 1 AS id;
CREATE VIEW public.v_oscar_inchidere_zi AS SELECT 1 AS id;
CREATE VIEW public.v_parc_auto_raport AS SELECT 1 AS id;
CREATE VIEW public.v_polite_alerte AS SELECT 1 AS id;
CREATE VIEW public.v_pontaj_personal_santier AS SELECT 1 AS id;
CREATE VIEW public.v_probe_config_consum AS SELECT 1 AS id;
CREATE VIEW public.v_productie_stoc AS SELECT 1 AS id;
CREATE VIEW public.v_profile_sites_active AS SELECT 1 AS id;
CREATE VIEW public.v_proiecte_nas_mapping AS SELECT 1 AS id;
CREATE VIEW public.v_qr_reconciliere_lunara AS SELECT 1 AS id;
CREATE VIEW public.v_radar_sezonier AS SELECT 1 AS id;
CREATE VIEW public.v_recycle_bin_hr AS SELECT 1 AS id;
CREATE VIEW public.v_rezervor_consistenta AS SELECT 1 AS id;
CREATE VIEW public.v_rompetrol_fara_whatsapp AS SELECT 1 AS id;
CREATE VIEW public.v_scadente_iminente AS SELECT 1 AS id;
CREATE VIEW public.v_sedinte_invitati_agenda AS SELECT 1 AS id;
CREATE VIEW public.v_sedinte_restante AS SELECT 1 AS id;
CREATE VIEW public.v_silentiate_active AS SELECT 1 AS id;
CREATE VIEW public.v_sl_fara_factura AS SELECT 1 AS id;
CREATE VIEW public.v_stoc_furnizori AS SELECT 1 AS id;
CREATE VIEW public.v_stocuri_sub_prag AS SELECT 1 AS id;
CREATE VIEW public.v_sudori_pentru_oferte AS SELECT 1 AS id;
CREATE VIEW public.v_supape_status AS SELECT 1 AS id;
CREATE VIEW public.v_tichete_alerte AS SELECT 1 AS id;
CREATE VIEW public.v_tichete_summary AS SELECT 1 AS id;
CREATE VIEW public.v_tkt139_progres AS SELECT 1 AS id;
CREATE VIEW public.v_upa_consum_lunar AS SELECT 1 AS id;
CREATE VIEW public.v_utilaje_pentru_oferte AS SELECT 1 AS id;
CREATE VIEW public.v_utilaje_santier_recent AS SELECT 1 AS id;
CREATE VIEW public.v_vehicule_comodat AS SELECT 1 AS id;
CREATE VIEW public.v_vehicule_contracte AS SELECT 1 AS id;
CREATE VIEW public.v_whatsapp_analytics AS SELECT 1 AS id;
CREATE TABLE public.whatsapp_imports_log (id integer);
CREATE TABLE public.whatsapp_messages_processed (id integer);
CREATE TABLE public.worker_heartbeat (id integer);
CREATE TABLE public._backup_analiza_plansa (id integer);
CREATE TABLE public.app_secrets (id integer);
CREATE TABLE public.ofertare_derogari_audit (id integer);
CREATE TABLE public.storage_egress_config (id integer);
CREATE VIEW public.v_claude_context_start AS SELECT 1 AS id;
CREATE VIEW public.v_ofertare_clarificari_baza AS SELECT 1 AS id;
REVOKE MAINTAIN ON public.ctc_carti FROM anon;
REVOKE MAINTAIN ON public.ctc_documente_carte FROM anon;
REVOKE MAINTAIN ON public.ctc_template_pozitii FROM anon;
REVOKE MAINTAIN ON public.ctc_templates FROM anon;
REVOKE MAINTAIN ON public.hr_formare_profesionala FROM anon;
REVOKE MAINTAIN ON public.logistica_imprumuturi FROM anon;
REVOKE MAINTAIN ON public.oferta_materiale FROM anon;
REVOKE MAINTAIN ON public.ofertare_brokeri FROM anon;
REVOKE MAINTAIN ON public.ofertare_calibrari FROM anon;
REVOKE MAINTAIN ON public.ofertare_calibrari_subcontractori FROM anon;
REVOKE MAINTAIN ON public.ofertare_categorii_reguli FROM anon;
REVOKE MAINTAIN ON public.ofertare_clarificari_puncte FROM anon;
REVOKE MAINTAIN ON public.ofertare_experienta FROM anon;
REVOKE MAINTAIN ON public.ofertare_normative FROM anon;
REVOKE MAINTAIN ON public.ofertare_norme_productivitate FROM anon;
REVOKE MAINTAIN ON public.ofertare_oferte_deschidere FROM anon;
REVOKE MAINTAIN ON public.ofertare_oferte_furnizori FROM anon;
REVOKE MAINTAIN ON public.ofertare_parteneri FROM anon;
REVOKE MAINTAIN ON public.ofertare_preturi_materiale FROM anon;
REVOKE MAINTAIN ON public.ofertare_preturi_unitare FROM anon;
REVOKE MAINTAIN ON public.ofertare_pt_afirmatii FROM anon;
REVOKE MAINTAIN ON public.ofertare_pt_capitole FROM anon;
REVOKE MAINTAIN ON public.ofertare_pt_capitole_versiuni FROM anon;
REVOKE MAINTAIN ON public.ofertare_pt_legaturi FROM anon;
REVOKE MAINTAIN ON public.ofertare_pt_observatii FROM anon;
REVOKE MAINTAIN ON public.ofertare_pt_poarta FROM anon;
REVOKE MAINTAIN ON public.ofertare_radar FROM anon;
REVOKE MAINTAIN ON public.ofertare_rfq FROM anon;
REVOKE MAINTAIN ON public.ofertare_rfq_destinatari FROM anon;
REVOKE MAINTAIN ON public.ofertare_rfq_materiale FROM anon;
REVOKE MAINTAIN ON public.ofertare_rfq_oferte FROM anon;
REVOKE MAINTAIN ON public.ofertare_rfq_preturi FROM anon;
REVOKE MAINTAIN ON public.ofertare_seap_manifest FROM anon;
REVOKE MAINTAIN ON public.ofertare_source_pack FROM anon;
REVOKE MAINTAIN ON public.ofertare_source_pack_importuri FROM anon;
REVOKE MAINTAIN ON public.probe_oferte FROM anon;
REVOKE MAINTAIN ON public.v_ctc_carti_progres FROM anon;
REVOKE MAINTAIN ON public.v_hr_formare_cursuri FROM anon;
REVOKE MAINTAIN ON public.v_ofertare_cerinte_dovezi FROM anon;
REVOKE MAINTAIN ON public.v_ofertare_pt_cerinte_neconfirmate FROM anon;
REVOKE MAINTAIN ON public.v_ofertare_seap_completitudine FROM anon;
REVOKE ALL ON public._backup_analiza_plansa FROM anon, authenticated;
REVOKE ALL ON public.app_secrets FROM anon, authenticated;
REVOKE ALL ON public.ofertare_derogari_audit FROM anon, authenticated;
REVOKE ALL ON public.storage_egress_config FROM anon, authenticated;
REVOKE ALL ON public.v_claude_context_start FROM anon, authenticated;
REVOKE ALL ON public.v_ofertare_clarificari_baza FROM anon, authenticated;
