// Fixture reală din planșa 470 (licitația 95, „Schema tehnologica Valcelele alimentare din Stefan Voda.pdf”), citirea salvată
// în analiza->'citire_ai'->'felii' (COD_VERSIUNE 2026-09-25.5, taiat_la 2026-09-25T16:45:36.622Z), SELECT 25.09.2026.
// Tabelul „Dimensionare” e tăiat de grilă în două coloane de zone: z?_6 are Nr crt + noduri + Sat/Strada/De la/Pana la
// (FĂRĂ lungimi), z?_7 are Strada/De la/Pana la + Dn + debit + lungime (FĂRĂ Nr). Benzile z1..z4 se suprapun vertical
// (Nr 32–37, 78–83, 123–129 apar în două benzi). Redus la minim: DOAR feliile z1_6..z4_7; din rândurile z?_6 doar
// Nr crt, Strada, Str. De la, Str. Pana la (câmpurile comune cu z?_7 + Nr); antetele (coloane) exact ca în BD;
// tronsoanele z?_7 exact ca în BD (sursa 'tabel', material null); tronsoanele z?_6 (fără lungime) omise.
// Verificat la transcriere (SELECT vs fișier): pe fiecare felie numărul de rânduri, suma Nr (z?_6), suma lungimilor
// (z?_7) și md5 pe câmpurile păstrate sunt identice cu BD (vezi docs/R4_REZERVARE_ZONE_SI_COADA_NAS.md §5).
// Felia z2_7 conține de 3 ori rândul „Florenta Albu → CT, C-tin Brancoveanu, 300 m, Dn40, Q20” = Nr 37, 40, 41 (z2_6).

export const COL6 = ["Nr crt", "Noduri de Plecare", "Noduri de Sosire", "Sat", "Strada", "Str. De la", "Str. Pana la"]
export const COL7 = ["Strada", "Str. De la", "Str. Pana la", "Dn ales (mm)", "Debit mc/h", "Lungime Km"]
export const DEN6 = 'Dimensionare'
export const DEN7: Record<string, string> = {"z1_7": "Dimensionare - Tronson retea de distributie", "z2_7": "Dimensionare - Tronson retea de distributie (continuare)", "z3_7": "Dimensionare - Tronson retea de distributie (continuare)", "z4_7": "Dimensionare - Tronson retea de distributie (continuare)"}
// z?_6: [Nr crt, Strada, Str. De la, Str. Pana la]
export const RANDURI_Z6: Record<string, [string, string, string, string][]> = {
  z1_6: [
    ["1", "UAT Stefan Voda", "SRMP", "UAT Cuza Voda"],
    ["2", "UAT Cuza Voda", "UAT Cuza Voda-Limita", "UAT Gradistea"],
    ["3", "UAT Gradistea", "UAT Gradistea-Limita", "UAT Independenta"],
    ["4", "UAT Independenta", "UAT Independenta-Limita", "UAT Valcelele"],
    ["5", "UAT Valcelele", "UAT Valcelele-Limita", "Limita Intravilan"],
    ["6", "Intravilan sat Floroaica", "Limita intravilan", "Ramif. SRS 1 Valcelele"],
    ["7", "Intravilan sat Floroaica", "Ramif. SRS 1 Valcelele - sat Floroaica", "Limita extravilan"],
    ["8", "UAT Valcelele", "Limita extravilan", "Ramif. Alimentare Dragos Voda"],
    ["9", "UAT Valcelele", "Ramif. Alimentare Dragos Voda", "Limita intravilan"],
    ["10", "Intravilan Valcelele", "Limita intravilan Valcelele", "SRS 2 Valcelele"],
    ["11", "Calarasilor", "SRS 2 Valcelele", "Libertatii"],
    ["12", "Calarasilor", "Libertatii", "Soseaua de centura"],
    ["13", "Calarasilor", "Soseaua de centura", "C-tin Brancusi"],
    ["14", "C-tin Brancusi", "Calarasilor", "FN"],
    ["15", "C-tin Brancusi", "FN", "Florenta Albu"],
    ["16", "C-tin Brancusi", "Florenta Albu", "CT"],
    ["17", "Florenta Albu", "C-tin Brancusi", "Sf Dimitrie"],
    ["18", "Florenta Albu", "Sf Dimitrie", "Calarasilor"],
    ["19", "Sf Dimitrie", "Florenta Albu", "CT"],
    ["20", "Sf Dimitrie", "Florenta Albu", "CT"],
    ["21", "Florenta Albu", "Calarasilor", "Spiru Haret"],
    ["22", "Calarasilor", "Florenta Albu", "CT"],
    ["23", "Calarasilor", "Florenta Albu", "CT"],
    ["24", "Florenta Albu", "Spiru Haret", "Mihai Eminescu"],
    ["25", "Spiru Haret", "Florenta Albu", "CT"],
    ["26", "Spiru Haret", "Florenta Albu", "CT"],
    ["27", "Florenta Albu", "Mihai Eminescu", "Nicolae Titulescu"],
    ["28", "Mihai Eminescu", "Florenta Albu", "CT"],
    ["29", "Mihai Eminescu", "Florenta Albu", "CT"],
    ["30", "Florenta Albu", "Nicolae Titulescu", "Baraganului"],
    ["31", "Nicolae Titulescu", "Florenta Albu", "CT"],
    ["32", "Nicolae Titulescu", "Florenta Albu", "CT"],
    ["33", "Baraganului", "Florenta Albu", "CT"],
    ["34", "Baraganului", "Florenta Albu", "CT"],
    ["35", "Florenta Albu", "C-tin Brancusi", "Aurel Vlaicu"],
    ["36", "Florenta Albu", "Aurel Vlaicu", "C-tin Brancoveanu"],
    ["37", "C-tin Brancoveanu", "Florenta Albu", "CT"],
  ],
  z2_6: [
    ["32", "Nicolae Titulescu", "Florenta Albu", "CT"],
    ["33", "Baraganului", "Florenta Albu", "CT"],
    ["34", "Baraganului", "Florenta Albu", "CT"],
    ["35", "Florenta Albu", "C-tin Brancusi", "Aurel Vlaicu"],
    ["36", "Florenta Albu", "Aurel Vlaicu", "C-tin Brancoveanu"],
    ["37", "C-tin Brancoveanu", "Florenta Albu", "CT"],
    ["38", "C-tin Brancoveanu", "Florenta Albu", "CT"],
    ["39", "Florenta Albu", "C-tin Brancoveanu", "Cuza Voda"],
    ["40", "C-tin Brancoveanu", "Florenta Albu", "CT"],
    ["41", "C-tin Brancoveanu", "Florenta Albu", "CT"],
    ["42", "Florenta Albu", "Cuza Voda", "Mihai Viteazu"],
    ["43", "Cuza Voda", "Florenta Albu", "CT"],
    ["44", "Cuza Voda", "Florenta Albu", "CT"],
    ["45", "Florenta Albu", "Mihai Viteazu", "Vlad Tepes"],
    ["46", "Mihai Viteazu", "Florenta Albu", "CT"],
    ["47", "Mihai Viteazu", "Florenta Albu", "CT"],
    ["48", "Florenta Albu", "Vlad Tepes", "Mircea cel Batran"],
    ["49", "Vlad Tepes", "Florenta Albu", "CT"],
    ["50", "Vlad Tepes", "Florenta Albu", "CT"],
    ["51", "Florenta Albu", "Mircea cel Batran", "Liliacului"],
    ["52", "Mircea cel Batran", "Florenta Albu", "CT"],
    ["53", "Mircea cel Batran", "Florenta Albu", "CT"],
    ["54", "Florenta Albu", "Liliacului", "Crinului"],
    ["55", "Liliacului", "Florenta Albu", "CT"],
    ["56", "Liliacului", "Florenta Albu", "CT"],
    ["57", "Florenta Albu", "Crinului", "Rozelor"],
    ["58", "Crinului", "Florenta Albu", "CT"],
    ["59", "Crinului", "Florenta Albu", "CT"],
    ["60", "Florenta Albu", "Rozelor", "Macului"],
    ["61", "Rozelor", "Florenta Albu", "CT"],
    ["62", "Rozelor", "Florenta Albu", "CT"],
    ["63", "Florenta Albu", "Macului", "CT"],
    ["64", "Macului", "Macului", "CT"],
    ["65", "Soseaia de centura", "Calarasilor", "Aurel Vlaicu"],
    ["66", "Soseaia de centura", "Aurel Vlaicu", "C-tin Brancoveanu"],
    ["67", "Aurel Vlaicu", "Soseaia de centura", "FN"],
    ["68", "Aurel Vlaicu", "FN", "CT"],
    ["69", "Soseaia de centura", "C-tin Brancoveanu", "Cuza Voda"],
    ["70", "C-tin Brancoveanu", "Soseaia de centura", "DS 1981"],
    ["71", "C-tin Brancoveanu", "FN", "CT"],
    ["72", "Soseaia de centura", "Cuza Voda", "Mihai Viteazu"],
    ["73", "Cuza Voda", "Soseaia de centura", "FN"],
    ["74", "Cuza Voda", "FN", "CT"],
    ["75", "Soseaia de centura", "Mihai Viteazu", "Vlad Tepes"],
    ["76", "Mihai Viteazu", "Soseaia de centura", "FN"],
    ["77", "Mihai Viteazu", "FN", "CT"],
    ["78", "Vlad Tepes", "Soseaia de centura", "FN"],
    ["79", "Vlad Tepes", "FN", "CT"],
    ["80", "Libertatii", "Calarasilor", "Sf Dimitrie"],
    ["81", "Libertatii", "Sf Dimitrie", "I.L. Caragiale"],
    ["82", "Sf Dimitrie", "Libertatii", "Calarasilor"],
    ["83", "Sf Dimitrie", "Calarasilor", "CT"],
  ],
  z3_6: [
    ["78", "Vlad Tepes", "Soseaia de centura", "FN"],
    ["79", "Vlad Tepes", "FN", "CT"],
    ["80", "Libertatii", "Calarasilor", "Sf Dimitrie"],
    ["81", "Libertatii", "Sf Dimitrie", "I.L. Caragiale"],
    ["82", "Sf Dimitrie", "Libertatii", "Calarasilor"],
    ["83", "Sf Dimitrie", "Calarasilor", "CT"],
    ["84", "Libertatii", "I.L. Caragiale", "Spiru Haret"],
    ["85", "I.L. Caragiale", "Libertatii", "Calarasilor"],
    ["86", "I.L. Caragiale", "Calarasilor", "CT"],
    ["87", "Libertatii", "Spiru Haret", "Mihai Eminescu"],
    ["88", "Spiru Haret", "Libertatii", "Calarasilor"],
    ["89", "Spiru Haret", "Calarasilor", "CT"],
    ["90", "Libertatii", "Mihai Eminescu", "Nicolae Titulescu"],
    ["91", "Mihai Eminescu", "Libertatii", "Calarasilor"],
    ["92", "Mihai Eminescu", "Calarasilor", "CT"],
    ["93", "Libertatii", "Nicolae Titulescu", "Baraganului"],
    ["94", "Nicolae Titulescu", "Libertatii", "Calarasilor"],
    ["95", "Nicolae Titulescu", "Calarasilor", "CT"],
    ["96", "Baraganului", "Libertatii", "CT"],
    ["97", "Stejarului", "Marin Preda", "SRS 1"],
    ["98", "Stejarului", "SRS 1", "Mihail Sadoveanu"],
    ["99", "Mihail Sadoveanu", "Stejarului", "Crizantemelor"],
    ["100", "Crizantemelor", "Mihail Sadoveanu", "Ion Creanga"],
    ["101", "Crizantemelor", "Ion Creanga", "Stefan Cel Mare"],
    ["102", "Crizantemelor", "Stefan Cel Mare", "George Cosbuc"],
    ["103", "Crizantemelor", "George Cosbuc", "DJ 306"],
    ["104", "Crizantemelor", "DJ 306", "Mihail Kogalniceanu"],
    ["105", "Crizantemelor", "Mihail Kogalniceanu", "FN (Drum agricol)"],
    ["106", "FN (Drum agricol)", "Crizantemelor", "CT"],
    ["107", "FN (Drum agricol)", "Crizantemelor", "Sf Mihail si Gavril"],
    ["108", "FN (Drum agricol)", "Sf Mihail si Gavril", "Teiului"],
    ["109", "Sf Mihail si Gavril", "FN (Drum agricol)", "CT"],
    ["110", "Mihail Sadoveanu", "Stejarului", "Crangului"],
    ["111", "Mihail Sadoveanu", "Crizantemelor", "Sf Mihail si Gavril"],
    ["112", "Mihail Sadoveanu", "Sf Mihail si Gavril", "Teiului"],
    ["113", "Ion Creanga", "Crizantemelor", "Salcamului"],
    ["114", "Ion Creanga", "Salcamului", "DJ 306"],
    ["115", "Ion Creanga", "Crizantemelor", "Sf Mihail si Gavril"],
    ["116", "Ion Creanga", "Sf Mihail si Gavril", "Caisului"],
    ["117", "Stefan Cel Mare", "Crizantemelor", "Salcamului"],
    ["118", "Stefan Cel Mare", "Salcamului", "DJ 306"],
    ["119", "Stefan Cel Mare", "Crizantemelor", "Sf Mihail si Gavril"],
    ["120", "Stefan Cel Mare", "Sf Mihail si Gavril", "Teiului"],
    ["121", "Stefan Cel Mare", "Teiului", "Caisului"],
    ["122", "George Cosbuc", "Crizantemelor", "Stejarului"],
    ["123", "George Cosbuc", "Stejarului", "DJ 306"],
    ["124", "George Cosbuc", "Crizantemelor", "Sf Mihail si Gavril"],
    ["125", "George Cosbuc", "Sf Mihail si Gavril", "Teiului"],
    ["126", "George Cosbuc", "Teiului", "Caisului"],
    ["127", "DJ 306", "Crizantemelor", "Ion Creanga"],
    ["128", "DJ 306", "Crizantemelor", "Trandafirului"],
    ["129", "DJ 306", "Trandafirului", "Panduri"],
  ],
  z4_6: [
    ["123", "George Cosbuc", "Stejarului", "DJ 306"],
    ["124", "George Cosbuc", "Crizantemelor", "Sf Mihail si G..."],
    ["125", "George Cosbuc", "Sf Mihail si Gavril", "Teiului"],
    ["126", "George Cosbuc", "Teiului", "Caisului"],
    ["127", "DJ 306", "Crizantemelor", "Ion Creang..."],
    ["128", "DJ 306", "Crizantemelor", "Trandafiru..."],
    ["129", "DJ 306", "Trandafirului", "Panduri"],
    ["130", "DJ 306", "Panduri", "Caisului"],
    ["131", "Mihail Kogalniceanu", "Crizantemelor", "Sf Mihail si G..."],
    ["132", "Mihail Kogalniceanu", "Sf Mihail si Gavril", "Teiului"],
    ["133", "Mihail Kogalniceanu", "Teiului", "CT"],
  ],
}
// z?_7: [Strada, Str. De la, Str. Pana la, Dn ales (mm), Debit mc/h, Lungime Km] — rândurile din tabele[0].randuri
export const RANDURI_Z7: Record<string, [string, string, string, string, string, string][]> = {
  z1_7: [
    ["UAT Stefan Voda", "SRMP", "UAT Cuza Voda-Limita", "200", "7500", "5,485"],
    ["UAT Cuza Voda", "UAT Cuza Voda-Limita", "UAT Gradistea-Limita", "200", "7500", "4,080"],
    ["UAT Gradistea", "UAT Gradistea-Limita", "UAT Independenta-Limita", "200", "7500", "1,980"],
    ["UAT Independenta", "UAT Independenta-Limita", "UAT Valcelele-Limita", "200", "7500", "2,220"],
    ["UAT Valcelele", "UAT Valcelele-Limita", "Limita Intravilan", "200", "5000", "0,600"],
    ["Intravilan sat Floroaica", "Limita intravilan", "Ramif. SRS 1 Valcelele - sat Floroaica", "200", "5000", "1,400"],
    ["Intravilan sat Floroaica", "Ramif. SRS 1 Valcelele - sat Floroaica", "Limita extravilan", "200", "4500", "0,650"],
    ["UAT Valcelele", "Limita extravilan", "Ramif. Alimentare Dragos Voda", "200", "4500", "1,370"],
    ["UAT Valcelele", "Ramif. Alimentare Dragos Voda", "Limita intravilan Valcelele", "90", "1000", "1,000"],
    ["Intravilan Valcelele", "Limita intravilan Valcelele", "SRS 2 Valcelele", "90", "1000", "0,340"],
    ["Calarasilor", "SRS 2 Valcelele", "Libertatii", "125", "1000", "0,015"],
    ["Calarasilor", "Libertatii", "Soseaua de centura", "125", "840", "0,150"],
    ["Calarasilor", "Soseaua de centura", "C-tin Brancusi", "125", "690", "0,490"],
    ["C-tin Brancusi", "Calarasilor", "FN", "125", "590", "0,090"],
    ["C-tin Brancusi", "FN", "Florenta Albu", "125", "580", "0,540"],
    ["C-tin Brancusi", "Florenta Albu", "CT", "125", "20", "0,300"],
    ["Florenta Albu", "C-tin Brancusi", "Sf Dimitrie", "110", "260", "0,110"],
    ["Florenta Albu", "Sf Dimitrie", "Calarasilor", "110", "210", "0,110"],
    ["Sf Dimitrie", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Sf Dimitrie", "Florenta Albu", "CT", "40", "30", "0,450"],
    ["Florenta Albu", "Calarasilor", "Spiru Haret", "110", "160", "0,110"],
    ["Calarasilor", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Calarasilor", "Florenta Albu", "CT", "40", "30", "0,460"],
    ["Florenta Albu", "Spiru Haret", "Mihai Eminescu", "90", "110", "0,110"],
    ["Spiru Haret", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Spiru Haret", "Florenta Albu", "CT", "40", "30", "0,460"],
    ["Florenta Albu", "Mihai Eminescu", "Nicolae Titulescu", "90", "60", "0,110"],
    ["Mihai Eminescu", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Mihai Eminescu", "Florenta Albu", "CT", "40", "30", "0,430"],
    ["Florenta Albu", "Nicolae Titulescu", "Baraganului", "63", "20", "0,110"],
    ["Nicolae Titulescu", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Nicolae Titulescu", "Florenta Albu", "CT", "40", "20", "0,330"],
    ["Baraganului", "Florenta Albu", "CT", "40", "10", "0,150"],
    ["Baraganului", "Florenta Albu", "CT", "40", "10", "0,200"],
    ["Florenta Albu", "C-tin Brancusi", "Aurel Vlaicu", "110", "280", "0,110"],
    ["Florenta Albu", "Aurel Vlaicu", "C-tin Brancoveanu", "110", "240", "0,110"],
    ["C-tin Brancoveanu", "Florenta Albu", "CT", "40", "20", "0,300"],
  ],
  z2_7: [
    ["Nicolae Titulescu", "Florenta Albu", "CT", "40", "20", "0,330"],
    ["Baraganului", "Florenta Albu", "CT", "40", "10", "0,150"],
    ["Baraganului", "Florenta Albu", "CT", "40", "10", "0,200"],
    ["Florenta Albu", "C-tin Brancusi", "Aurel Vlaicu", "110", "280", "0,110"],
    ["Florenta Albu", "Aurel Vlaicu", "C-tin Brancoveanu", "110", "240", "0,110"],
    ["C-tin Brancoveanu", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["C-tin Brancoveanu", "Florenta Albu", "CT", "40", "20", "0,320"],
    ["Florenta Albu", "C-tin Brancoveanu", "Cuza Voda", "110", "200", "0,110"],
    ["C-tin Brancoveanu", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["C-tin Brancoveanu", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Florenta Albu", "Cuza Voda", "Mihai Viteazu", "90", "160", "0,110"],
    ["Cuza Voda", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Cuza Voda", "Florenta Albu", "CT", "40", "20", "0,200"],
    ["Florenta Albu", "Mihai Viteazu", "Vlad Tepes", "90", "120", "0,110"],
    ["Mihai Viteazu", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Mihai Viteazu", "Florenta Albu", "CT", "40", "20", "0,200"],
    ["Florenta Albu", "Vlad Tepes", "Mircea cel Batran", "90", "100", "0,110"],
    ["Vlad Tepes", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Vlad Tepes", "Florenta Albu", "CT", "40", "20", "0,220"],
    ["Florenta Albu", "Mircea cel Batran", "Liliacului", "63", "80", "0,110"],
    ["Mircea cel Batran", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Mircea cel Batran", "Florenta Albu", "CT", "40", "10", "0,200"],
    ["Florenta Albu", "Liliacului", "Crinului", "63", "60", "0,110"],
    ["Liliacului", "Florenta Albu", "CT", "40", "20", "0,300"],
    ["Liliacului", "Florenta Albu", "CT", "40", "10", "0,130"],
    ["Florenta Albu", "Crinului", "Rozelor", "60", "40", "0,110"],
    ["Crinului", "Florenta Albu", "CT", "40", "20", "0,280"],
    ["Crinului", "Florenta Albu", "CT", "40", "10", "0,130"],
    ["Florenta Albu", "Rozelor", "Macului", "63", "20", "0,110"],
    ["Rozelor", "Florenta Albu", "CT", "40", "20", "0,280"],
    ["Rozelor", "Florenta Albu", "CT", "40", "5", "0,100"],
    ["Florenta Albu", "Macului", "CT", "40", "5", "0,030"],
    ["Macului", "Macului", "CT", "40", "5", "0,280"],
    ["Soseaia de centura", "Calarasilor", "Aurel Vlaicu", "90", "150", "0,130"],
    ["Soseaia de centura", "Aurel Vlaicu", "C-tin Brancoveanu", "90", "120", "0,130"],
    ["Aurel Vlaicu", "Soseaia de centura", "FN", "63", "30", "0,550"],
    ["Aurel Vlaicu", "FN", "CT", "40", "10", "0,130"],
    ["Soseaia de centura", "C-tin Brancoveanu", "Cuza Voda", "63", "90", "0,130"],
    ["C-tin Brancoveanu", "Soseaia de centura", "DS 1981", "63", "30", "0,550"],
    ["C-tin Brancoveanu", "FN", "CT", "40", "10", "0,130"],
    ["Soseaia de centura", "Cuza Voda", "Mihai Viteazu", "63", "60", "0,130"],
    ["Cuza Voda", "Soseaia de centura", "FN", "63", "30", "0,510"],
    ["Cuza Voda", "FN", "CT", "40", "10", "0,220"],
    ["Soseaia de centura", "Mihai Viteazu", "Vlad Tepes", "63", "30", "0,130"],
    ["Mihai Viteazu", "Soseaia de centura", "FN", "63", "30", "0,600"],
    ["Mihai Viteazu", "FN", "CT", "40", "10", "0,120"],
    ["Vlad Tepes", "Soseaia de centura", "FN", "63", "30", "0,580"],
    ["Vlad Tepes", "FN", "CT", "40", "10", "0,090"],
    ["Libertatii", "Calarasilor", "Sf Dimitrie", "90", "160", "0,060"],
    ["Libertatii", "Sf Dimitrie", "I.L. Caragiale", "90", "130", "0,120"],
    ["Sf Dimitrie", "Libertatii", "Calarasilor", "63", "30", "0,640"],
    ["Sf Dimitrie", "Calarasilor", "CT", "40", "5", "0,100"],
  ],
  z3_7: [
    ["Vlad Tepes", "Soseaia de centura", "FN", "63", "30", "0,580"],
    ["Vlad Tepes", "FN", "CT", "40", "10", "0,090"],
    ["Libertatii", "Calarasilor", "Sf Dimitrie", "90", "160", "0,060"],
    ["Libertatii", "Sf Dimitrie", "I.L. Caragiale", "90", "130", "0,120"],
    ["Sf Dimitrie", "Libertatii", "Calarasilor", "63", "30", "0,640"],
    ["Sf Dimitrie", "Calarasilor", "CT", "40", "5", "0,100"],
    ["Libertatii", "I.L. Caragiale", "Spiru Haret", "90", "100", "0,120"],
    ["I.L. Caragiale", "Libertatii", "Calarasilor", "63", "30", "0,640"],
    ["I.L. Caragiale", "Calarasilor", "CT", "40", "5", "0,100"],
    ["Libertatii", "Spiru Haret", "Mihai Eminescu", "63", "70", "0,120"],
    ["Spiru Haret", "Libertatii", "Calarasilor", "63", "30", "0,640"],
    ["Spiru Haret", "Calarasilor", "CT", "40", "5", "0,100"],
    ["Libertatii", "Mihai Eminescu", "Nicolae Titulescu", "63", "40", "0,120"],
    ["Mihai Eminescu", "Libertatii", "Calarasilor", "63", "30", "0,640"],
    ["Mihai Eminescu", "Calarasilor", "CT", "40", "5", "0,100"],
    ["Libertatii", "Nicolae Titulescu", "Baraganului", "63", "10", "0,120"],
    ["Nicolae Titulescu", "Libertatii", "Calarasilor", "63", "30", "0,630"],
    ["Nicolae Titulescu", "Calarasilor", "CT", "40", "5", "0,200"],
    ["Baraganului", "Libertatii", "CT", "40", "10", "0,620"],
    ["Stejarului", "Marin Preda", "SRS 1", "90", "500", "0,005"],
    ["Stejarului", "SRS 1", "Mihail Sadoveanu", "125", "500", "0,110"],
    ["Mihail Sadoveanu", "Stejarului", "Crizantemelor", "125", "470", "0,140"],
    ["Crizantemelor", "Mihail Sadoveanu", "Ion Creanga", "125", "420", "0,110"],
    ["Crizantemelor", "Ion Creanga", "Stefan Cel Mare", "125", "350", "0,110"],
    ["Crizantemelor", "Stefan Cel Mare", "George Cosbuc", "125", "300", "0,110"],
    ["Crizantemelor", "George Cosbuc", "DJ 306", "125", "250", "0,110"],
    ["Crizantemelor", "DJ 306", "Mihail Kogalniceanu", "110", "150", "0,120"],
    ["Crizantemelor", "Mihail Kogalniceanu", "FN (Drum agricol)", "90", "50", "0,110"],
    ["FN (Drum agricol)", "Crizantemelor", "CT", "40", "10", "0,110"],
    ["FN (Drum agricol)", "Crizantemelor", "Sf Mihail si Gavril", "63", "20", "0,230"],
    ["FN (Drum agricol)", "Sf Mihail si Gavril", "Teiului", "40", "10", "0,270"],
    ["Sf Mihail si Gavril", "FN (Drum agricol)", "CT", "40", "5", "0,100"],
    ["Mihail Sadoveanu", "Stejarului", "Crangului", "40", "20", "0,260"],
    ["Mihail Sadoveanu", "Crizantemelor", "Sf Mihail si Gavril", "63", "40", "0,270"],
    ["Mihail Sadoveanu", "Sf Mihail si Gavril", "Teiului", "40", "20", "0,370"],
    ["Ion Creanga", "Crizantemelor", "Salcamului", "63", "30", "0,260"],
    ["Ion Creanga", "Salcamului", "DJ 306", "40", "10", "0,260"],
    ["Ion Creanga", "Crizantemelor", "Sf Mihail si Gavril", "63", "40", "0,270"],
    ["Ion Creanga", "Sf Mihail si Gavril", "Caisului", "40", "20", "0,370"],
    ["Stefan Cel Mare", "Crizantemelor", "Salcamului", "63", "30", "0,260"],
    ["Stefan Cel Mare", "Salcamului", "DJ 306", "40", "10", "0,180"],
    ["Stefan Cel Mare", "Crizantemelor", "Sf Mihail si Gavril", "90", "50", "0,270"],
    ["Stefan Cel Mare", "Sf Mihail si Gavril", "Teiului", "63", "30", "0,270"],
    ["Stefan Cel Mare", "Teiului", "Caisului", "40", "10", "0,180"],
    ["George Cosbuc", "Crizantemelor", "Stejarului", "63", "30", "0,130"],
    ["George Cosbuc", "Stejarului", "DJ 306", "40", "20", "0,220"],
    ["George Cosbuc", "Crizantemelor", "Sf Mihail si Gavril", "90", "50", "0,270"],
    ["George Cosbuc", "Sf Mihail si Gavril", "Teiului", "63", "30", "0,270"],
    ["George Cosbuc", "Teiului", "Caisului", "40", "10", "0,280"],
    ["DJ 306", "Crizantemelor", "Ion Creanga", "90", "40", "0,760"],
    ["DJ 306", "Crizantemelor", "Trandafirului", "90", "60", "0,410"],
    ["DJ 306", "Trandafirului", "Panduri", "63", "40", "0,270"],
  ],
  z4_7: [
    ["George Cosbuc", "Stejarului", "DJ 306", "40", "20", "0,220"],
    ["George Cosbuc", "Crizantemelor", "Sf Mihail si Gavril", "90", "50", "0,270"],
    ["George Cosbuc", "Sf Mihail si Gavril", "Teiului", "63", "30", "0,270"],
    ["George Cosbuc", "Teiului", "Caisului", "40", "10", "0,280"],
    ["DJ 306", "Crizantemelor", "Ion Creanga", "90", "40", "0,760"],
    ["DJ 306", "Crizantemelor", "Trandafirului", "90", "60", "0,410"],
    ["DJ 306", "Trandafirului", "Panduri", "63", "40", "0,270"],
    ["DJ 306", "Panduri", "Caisului", "40", "10", "0,220"],
    ["Mihail Kogalniceanu", "Crizantemelor", "Sf Mihail si Gavril", "90", "50", "0,270"],
    ["Mihail Kogalniceanu", "Sf Mihail si Gavril", "Teiului", "63", "30", "0,270"],
    ["Mihail Kogalniceanu", "Teiului", "CT", "40", "10", "0,260"],
  ],
}
// z?_7: tronsoanele (sursa 'tabel'), [de_la, la, lungime_m, diametru_mm, debit_mch, zona] — în ordinea din BD
export const FELII_470: Record<string, [string, string, number, number, number, string][]> = {
  z1_7: [
    ["SRMP", "UAT Cuza Voda-Limita", 5485, 200, 7500, "UAT Stefan Voda"],
    ["UAT Cuza Voda-Limita", "UAT Gradistea-Limita", 4080, 200, 7500, "UAT Cuza Voda"],
    ["UAT Gradistea-Limita", "UAT Independenta-Limita", 1980, 200, 7500, "UAT Gradistea"],
    ["UAT Independenta-Limita", "UAT Valcelele-Limita", 2220, 200, 7500, "UAT Independenta"],
    ["UAT Valcelele-Limita", "Limita Intravilan", 600, 200, 5000, "UAT Valcelele"],
    ["Limita intravilan", "Ramif. SRS 1 Valcelele - sat Floroaica", 1400, 200, 5000, "Intravilan sat Floroaica"],
    ["Ramif. SRS 1 Valcelele - sat Floroaica", "Limita extravilan", 650, 200, 4500, "Intravilan sat Floroaica"],
    ["Limita extravilan", "Ramif. Alimentare Dragos Voda", 1370, 200, 4500, "UAT Valcelele"],
    ["Ramif. Alimentare Dragos Voda", "Limita intravilan Valcelele", 1000, 90, 1000, "UAT Valcelele"],
    ["Limita intravilan Valcelele", "SRS 2 Valcelele", 340, 90, 1000, "Intravilan Valcelele"],
    ["SRS 2 Valcelele", "Libertatii", 15, 125, 1000, "Calarasilor"],
    ["Libertatii", "Soseaua de centura", 150, 125, 840, "Calarasilor"],
    ["Soseaua de centura", "C-tin Brancusi", 490, 125, 690, "Calarasilor"],
    ["Calarasilor", "FN", 90, 125, 590, "C-tin Brancusi"],
    ["FN", "Florenta Albu", 540, 125, 580, "C-tin Brancusi"],
    ["Florenta Albu", "CT", 300, 125, 20, "C-tin Brancusi"],
    ["C-tin Brancusi", "Sf Dimitrie", 110, 110, 260, "Florenta Albu"],
    ["Sf Dimitrie", "Calarasilor", 110, 110, 210, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Sf Dimitrie"],
    ["Florenta Albu", "CT", 450, 40, 30, "Sf Dimitrie"],
    ["Calarasilor", "Spiru Haret", 110, 110, 160, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Calarasilor"],
    ["Florenta Albu", "CT", 460, 40, 30, "Calarasilor"],
    ["Spiru Haret", "Mihai Eminescu", 110, 90, 110, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Spiru Haret"],
    ["Florenta Albu", "CT", 460, 40, 30, "Spiru Haret"],
    ["Mihai Eminescu", "Nicolae Titulescu", 110, 90, 60, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Mihai Eminescu"],
    ["Florenta Albu", "CT", 430, 40, 30, "Mihai Eminescu"],
    ["Nicolae Titulescu", "Baraganului", 110, 63, 20, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Nicolae Titulescu"],
    ["Florenta Albu", "CT", 330, 40, 20, "Nicolae Titulescu"],
    ["Florenta Albu", "CT", 150, 40, 10, "Baraganului"],
    ["Florenta Albu", "CT", 200, 40, 10, "Baraganului"],
    ["C-tin Brancusi", "Aurel Vlaicu", 110, 110, 280, "Florenta Albu"],
    ["Aurel Vlaicu", "C-tin Brancoveanu", 110, 110, 240, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "C-tin Brancoveanu"],
  ],
  z2_7: [
    ["Florenta Albu", "CT", 330, 40, 20, "Nicolae Titulescu"],
    ["Florenta Albu", "CT", 150, 40, 10, "Baraganului"],
    ["Florenta Albu", "CT", 200, 40, 10, "Baraganului"],
    ["C-tin Brancusi", "Aurel Vlaicu", 110, 110, 280, "Florenta Albu"],
    ["Aurel Vlaicu", "C-tin Brancoveanu", 110, 110, 240, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "C-tin Brancoveanu"],
    ["Florenta Albu", "CT", 320, 40, 20, "C-tin Brancoveanu"],
    ["C-tin Brancoveanu", "Cuza Voda", 110, 110, 200, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "C-tin Brancoveanu"],
    ["Florenta Albu", "CT", 300, 40, 20, "C-tin Brancoveanu"],
    ["Cuza Voda", "Mihai Viteazu", 110, 90, 160, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Cuza Voda"],
    ["Florenta Albu", "CT", 200, 40, 20, "Cuza Voda"],
    ["Mihai Viteazu", "Vlad Tepes", 110, 90, 120, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Mihai Viteazu"],
    ["Florenta Albu", "CT", 200, 40, 20, "Mihai Viteazu"],
    ["Vlad Tepes", "Mircea cel Batran", 110, 90, 100, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Vlad Tepes"],
    ["Florenta Albu", "CT", 220, 40, 20, "Vlad Tepes"],
    ["Mircea cel Batran", "Liliacului", 110, 63, 80, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Mircea cel Batran"],
    ["Florenta Albu", "CT", 200, 40, 10, "Mircea cel Batran"],
    ["Liliacului", "Crinului", 110, 63, 60, "Florenta Albu"],
    ["Florenta Albu", "CT", 300, 40, 20, "Liliacului"],
    ["Florenta Albu", "CT", 130, 40, 10, "Liliacului"],
    ["Crinului", "Rozelor", 110, 60, 40, "Florenta Albu"],
    ["Florenta Albu", "CT", 280, 40, 20, "Crinului"],
    ["Florenta Albu", "CT", 130, 40, 10, "Crinului"],
    ["Rozelor", "Macului", 110, 63, 20, "Florenta Albu"],
    ["Florenta Albu", "CT", 280, 40, 20, "Rozelor"],
    ["Florenta Albu", "CT", 100, 40, 5, "Rozelor"],
    ["Macului", "CT", 30, 40, 5, "Florenta Albu"],
    ["Macului", "CT", 280, 40, 5, "Macului"],
    ["Calarasilor", "Aurel Vlaicu", 130, 90, 150, "Soseaia de centura"],
    ["Aurel Vlaicu", "C-tin Brancoveanu", 130, 90, 120, "Soseaia de centura"],
    ["Soseaia de centura", "FN", 550, 63, 30, "Aurel Vlaicu"],
    ["FN", "CT", 130, 40, 10, "Aurel Vlaicu"],
    ["C-tin Brancoveanu", "Cuza Voda", 130, 63, 90, "Soseaia de centura"],
    ["Soseaia de centura", "DS 1981", 550, 63, 30, "C-tin Brancoveanu"],
    ["FN", "CT", 130, 40, 10, "C-tin Brancoveanu"],
    ["Cuza Voda", "Mihai Viteazu", 130, 63, 60, "Soseaia de centura"],
    ["Soseaia de centura", "FN", 510, 63, 30, "Cuza Voda"],
    ["FN", "CT", 220, 40, 10, "Cuza Voda"],
    ["Mihai Viteazu", "Vlad Tepes", 130, 63, 30, "Soseaia de centura"],
    ["Soseaia de centura", "FN", 600, 63, 30, "Mihai Viteazu"],
    ["FN", "CT", 120, 40, 10, "Mihai Viteazu"],
    ["Soseaia de centura", "FN", 580, 63, 30, "Vlad Tepes"],
    ["FN", "CT", 90, 40, 10, "Vlad Tepes"],
    ["Calarasilor", "Sf Dimitrie", 60, 90, 160, "Libertatii"],
    ["Sf Dimitrie", "I.L. Caragiale", 120, 90, 130, "Libertatii"],
    ["Libertatii", "Calarasilor", 640, 63, 30, "Sf Dimitrie"],
    ["Calarasilor", "CT", 100, 40, 5, "Sf Dimitrie"],
  ],
  z3_7: [
    ["Soseaia de centura", "FN", 580, 63, 30, "Vlad Tepes"],
    ["FN", "CT", 90, 40, 10, "Vlad Tepes"],
    ["Calarasilor", "Sf Dimitrie", 60, 90, 160, "Libertatii"],
    ["Sf Dimitrie", "I.L. Caragiale", 120, 90, 130, "Libertatii"],
    ["Libertatii", "Calarasilor", 640, 63, 30, "Sf Dimitrie"],
    ["Calarasilor", "CT", 100, 40, 5, "Sf Dimitrie"],
    ["I.L. Caragiale", "Spiru Haret", 120, 90, 100, "Libertatii"],
    ["Libertatii", "Calarasilor", 640, 63, 30, "I.L. Caragiale"],
    ["Calarasilor", "CT", 100, 40, 5, "I.L. Caragiale"],
    ["Spiru Haret", "Mihai Eminescu", 120, 63, 70, "Libertatii"],
    ["Libertatii", "Calarasilor", 640, 63, 30, "Spiru Haret"],
    ["Calarasilor", "CT", 100, 40, 5, "Spiru Haret"],
    ["Mihai Eminescu", "Nicolae Titulescu", 120, 63, 40, "Libertatii"],
    ["Libertatii", "Calarasilor", 640, 63, 30, "Mihai Eminescu"],
    ["Calarasilor", "CT", 100, 40, 5, "Mihai Eminescu"],
    ["Nicolae Titulescu", "Baraganului", 120, 63, 10, "Libertatii"],
    ["Libertatii", "Calarasilor", 630, 63, 30, "Nicolae Titulescu"],
    ["Calarasilor", "CT", 200, 40, 5, "Nicolae Titulescu"],
    ["Libertatii", "CT", 620, 40, 10, "Baraganului"],
    ["Marin Preda", "SRS 1", 5, 90, 500, "Stejarului"],
    ["SRS 1", "Mihail Sadoveanu", 110, 125, 500, "Stejarului"],
    ["Stejarului", "Crizantemelor", 140, 125, 470, "Mihail Sadoveanu"],
    ["Mihail Sadoveanu", "Ion Creanga", 110, 125, 420, "Crizantemelor"],
    ["Ion Creanga", "Stefan Cel Mare", 110, 125, 350, "Crizantemelor"],
    ["Stefan Cel Mare", "George Cosbuc", 110, 125, 300, "Crizantemelor"],
    ["George Cosbuc", "DJ 306", 110, 125, 250, "Crizantemelor"],
    ["DJ 306", "Mihail Kogalniceanu", 120, 110, 150, "Crizantemelor"],
    ["Mihail Kogalniceanu", "FN (Drum agricol)", 110, 90, 50, "Crizantemelor"],
    ["Crizantemelor", "CT", 110, 40, 10, "FN (Drum agricol)"],
    ["Crizantemelor", "Sf Mihail si Gavril", 230, 63, 20, "FN (Drum agricol)"],
    ["Sf Mihail si Gavril", "Teiului", 270, 40, 10, "FN (Drum agricol)"],
    ["FN (Drum agricol)", "CT", 100, 40, 5, "Sf Mihail si Gavril"],
    ["Stejarului", "Crangului", 260, 40, 20, "Mihail Sadoveanu"],
    ["Crizantemelor", "Sf Mihail si Gavril", 270, 63, 40, "Mihail Sadoveanu"],
    ["Sf Mihail si Gavril", "Teiului", 370, 40, 20, "Mihail Sadoveanu"],
    ["Crizantemelor", "Salcamului", 260, 63, 30, "Ion Creanga"],
    ["Salcamului", "DJ 306", 260, 40, 10, "Ion Creanga"],
    ["Crizantemelor", "Sf Mihail si Gavril", 270, 63, 40, "Ion Creanga"],
    ["Sf Mihail si Gavril", "Caisului", 370, 40, 20, "Ion Creanga"],
    ["Crizantemelor", "Salcamului", 260, 63, 30, "Stefan Cel Mare"],
    ["Salcamului", "DJ 306", 180, 40, 10, "Stefan Cel Mare"],
    ["Crizantemelor", "Sf Mihail si Gavril", 270, 90, 50, "Stefan Cel Mare"],
    ["Sf Mihail si Gavril", "Teiului", 270, 63, 30, "Stefan Cel Mare"],
    ["Teiului", "Caisului", 180, 40, 10, "Stefan Cel Mare"],
    ["Crizantemelor", "Stejarului", 130, 63, 30, "George Cosbuc"],
    ["Stejarului", "DJ 306", 220, 40, 20, "George Cosbuc"],
    ["Crizantemelor", "Sf Mihail si Gavril", 270, 90, 50, "George Cosbuc"],
    ["Sf Mihail si Gavril", "Teiului", 270, 63, 30, "George Cosbuc"],
    ["Teiului", "Caisului", 280, 40, 10, "George Cosbuc"],
    ["Crizantemelor", "Ion Creanga", 760, 90, 40, "DJ 306"],
    ["Crizantemelor", "Trandafirului", 410, 90, 60, "DJ 306"],
    ["Trandafirului", "Panduri", 270, 63, 40, "DJ 306"],
  ],
  z4_7: [
    ["Stejarului", "DJ 306", 220, 40, 20, "George Cosbuc"],
    ["Crizantemelor", "Sf Mihail si Gavril", 270, 90, 50, "George Cosbuc"],
    ["Sf Mihail si Gavril", "Teiului", 270, 63, 30, "George Cosbuc"],
    ["Teiului", "Caisului", 280, 40, 10, "George Cosbuc"],
    ["Crizantemelor", "Ion Creanga", 760, 90, 40, "DJ 306"],
    ["Crizantemelor", "Trandafirului", 410, 90, 60, "DJ 306"],
    ["Trandafirului", "Panduri", 270, 63, 40, "DJ 306"],
    ["Panduri", "Caisului", 220, 40, 10, "DJ 306"],
    ["Crizantemelor", "Sf Mihail si Gavril", 270, 90, 50, "Mihail Kogalniceanu"],
    ["Sf Mihail si Gavril", "Teiului", 270, 63, 30, "Mihail Kogalniceanu"],
    ["Teiului", "CT", 260, 40, 10, "Mihail Kogalniceanu"],
  ],
}
// Cifrele din BD de AZI (agregarea veche, pe mulțime) — citire_ai.sumar.cantitati.pe_diametre la doc 470 și ofertare_cantitati
// 1751–1756 (cantitate = cantitate_plansa), SELECT 25.09.2026; lungime_totala_m = 48195, tronsoane_gasite = 130.
export const AZI_470 = { Dn200: 17785, Dn125: 2275, Dn110: 780, Dn90: 4545, Dn63: 9670, Dn40: 13140 } as Record<string, number>
// Feliile ca în citire_ai.felii (reduse): z?_6 = tabel cu Nr (fără tronsoane cu lungime), z?_7 = tabel + tronsoane.
export const feliiDin470 = (opt: { doar?: string[] } = {}) => ['1', '2', '3', '4'].flatMap((b) => [
  { eticheta: `z${b}_6`, tronsoane: [] as any[], tabele: [{ denumire: DEN6, coloane: COL6,
    randuri: RANDURI_Z6[`z${b}_6`].map(([nr, st, dl, pl]) => ({ 'Nr crt': nr, 'Strada': st, 'Str. De la': dl, 'Str. Pana la': pl })) }] },
  { eticheta: `z${b}_7`, tabele: [{ denumire: DEN7[`z${b}_7`], coloane: COL7,
    randuri: RANDURI_Z7[`z${b}_7`].map(([st, dl, pl, dn, q, l]) => ({ 'Strada': st, 'Str. De la': dl, 'Str. Pana la': pl, 'Dn ales (mm)': dn, 'Debit mc/h': q, 'Lungime Km': l })) }],
    tronsoane: FELII_470[`z${b}_7`].map(([de_la, la, lungime_m, diametru_mm, debit_mch, zona]) =>
      ({ de_la, la, lungime_m, diametru_mm, debit_mch, zona, sursa: 'tabel', material: null })) },
]).filter((f) => !opt.doar || opt.doar.includes(f.eticheta))
// Răspunsul AI simulat pentru o zonă (testele de handler): exact felia din fixture, plus cartușul pe z1_7.
export const raspuns470 = (et: string) => {
  const f = feliiDin470({ doar: [et] })[0]
  return f ? { tronsoane: f.tronsoane, tabele: f.tabele, cartus: et === 'z1_7' ? { plansa_nr: '1' } : {} } : { tronsoane: [], tabele: [], cartus: {} }
}
