#!/usr/bin/env bash
# ============================================================================
# Harness SQL local — 20261020a_ofertare_completitudine_arhive (audit #11). EXCLUSIV pe un PostgreSQL 17 local dedicat
# (implicit /tmp/pg_compl_arh, 127.0.0.1:5974). Nu atinge producția.
#   0. schelet = tipurile coloanelor din producție + view-ul din 20260924 → md5(pg_get_viewdef) = cel live (52cf46a8…)
#   1. fișierul fără runner → garda refuză
#   2. livrare prin scripts/livrare_migrare.sh (sha256 + gate 0e) → cod 0; scenariile #11 dau blocajul așteptat;
#      licitațiile fără arhive au exact blocajul de dinainte; authenticated citește, anon nu
#   3. reaplicare → refuz (precondiția md5 vede definiția nouă)
#   4. revenire nearmată → refuz; armată → semantica veche (aceleași blocaje ca la 0), coloanele noi neutre
# Utilizare: bash scripts/test_ofertare_completitudine_arhive.sh [--opreste]   Ieșire: 0 PASS · 1 eșec · 2 mediu
# ============================================================================
set -Eeuo pipefail
RADACINA="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PG_BIN="${PG_BIN:-/usr/lib/postgresql/17/bin}"
DATE_DIR="${PGDATA_TEST:-/tmp/pg_compl_arh}"
PORT="${PGPORT_TEST:-5974}"
BAZA=compl_arh_test
NUME=20261020a_ofertare_completitudine_arhive
MIGRARE="$RADACINA/supabase/migrations/$NUME.sql"
ROLLBACK="$RADACINA/supabase/revenire/${NUME}_ROLLBACK.sql"
OPRESTE=0; [ "${1:-}" = --opreste ] && OPRESTE=1
esec()  { echo "ESEC: $*" >&2; exit 1; }
mediu() { echo "MEDIU: $*" >&2; exit 2; }
ok()    { echo "OK   $*"; }
ca_postgres() { if [ "$(id -u)" = 0 ]; then su postgres -s /bin/bash -c "$(printf '%q ' "$@")"; else "$@"; fi; }
PSQL=("$PG_BIN/psql" -X -q -v ON_ERROR_STOP=1 -h 127.0.0.1 -p "$PORT" -U postgres)
trap '[ $OPRESTE = 1 ] && ca_postgres "$PG_BIN/pg_ctl" -D "$DATE_DIR" -m fast -w stop >/dev/null 2>&1; true' EXIT
q() { "${PSQL[@]}" -d "$BAZA" -Atc "$1"; }
gate_0e() { local n; n="$("${PSQL[@]}" -d "$BAZA" -At -f "$RADACINA/scripts/control_0e.sql" | grep -c . || true)"; [ "$n" = 0 ] || esec "gate 0e: $n rânduri"; ok "gate 0e = 0 ($1)"; }
ca() { "${PSQL[@]}" -d "$BAZA" -At 2>&1 <<SQL | tail -1
BEGIN;
SELECT set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', true) \g /dev/null
SET LOCAL ROLE $1;
$2;
ROLLBACK;
SQL
}
BLOC="SELECT string_agg(licitatie_id || '=' || coalesce(blocaj, '-'), ' | ' ORDER BY licitatie_id) FROM v_ofertare_seap_completitudine"

[ -x "$PG_BIN/initdb" ] || mediu "PG17 lipsă ($PG_BIN)"
if [ -f "$DATE_DIR/postmaster.pid" ]; then ca_postgres "$PG_BIN/pg_ctl" -D "$DATE_DIR" -m fast -w stop >/dev/null || true; fi
rm -rf "$DATE_DIR"; mkdir -p "$DATE_DIR"; [ "$(id -u)" = 0 ] && chown postgres "$DATE_DIR"
ca_postgres "$PG_BIN/initdb" -D "$DATE_DIR" -U postgres --auth=trust --encoding=UTF8 --locale=C.UTF-8 >/dev/null || mediu initdb
ca_postgres "$PG_BIN/pg_ctl" -D "$DATE_DIR" -l /tmp/pg_compl_arh.log -w -t 30 start \
  -o "-p $PORT -c listen_addresses=127.0.0.1 -c unix_socket_directories=/tmp" >/dev/null || mediu "pg_ctl start"
"${PSQL[@]}" -d postgres -c "CREATE DATABASE $BAZA" >/dev/null

# ── 0. schelet: tipurile din producție (information_schema, 07.10) + view-ul exact din 20260924_ofertare_ignorat_tehnic_bifa ──
"${PSQL[@]}" -d "$BAZA" >/dev/null <<'SQL'
SET client_min_messages = warning;
CREATE ROLE anon NOLOGIN NOINHERIT; CREATE ROLE authenticated NOLOGIN NOINHERIT; CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
CREATE SCHEMA auth; GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT EXECUTE ON FUNCTION auth.uid() TO anon, authenticated, service_role;
CREATE TABLE public.ofertare_licitatii (id bigint PRIMARY KEY, c_notice_id bigint);
CREATE TABLE public.ofertare_seap_cereri (licitatie_id bigint PRIMARY KEY REFERENCES public.ofertare_licitatii(id), cerut_la timestamptz NOT NULL DEFAULT now(),
  cerut_de uuid, sursa text NOT NULL DEFAULT 'om', preluat_la timestamptz, terminat_la timestamptz, raport jsonb);
CREATE TABLE public.ofertare_seap_fisiere (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, licitatie_id bigint NOT NULL REFERENCES public.ofertare_licitatii(id),
  nume_seap text NOT NULL, cheie text NOT NULL, stare text NOT NULL, motiv text, marime bigint, sha256 text, fisiere_extrase int,
  incercari int NOT NULL DEFAULT 1, procesat_la timestamptz NOT NULL DEFAULT now(), etapa text, UNIQUE (licitatie_id, cheie));
CREATE TABLE public.ofertare_documente_atribuire (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, licitatie_id bigint, fisier_path text,
  nume_original text, tip text, text_extras text, eroare text, status_procesare text, relevanta_verificata_la timestamptz);
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['ofertare_licitatii','ofertare_seap_cereri','ofertare_seap_fisiere','ofertare_documente_atribuire'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY sel ON public.%I FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL)', t);
    EXECUTE format('GRANT SELECT ON public.%I TO authenticated, service_role', t);
  END LOOP; END $$;
-- ca live după 20261013b: SECURITY INVOKER, EXECUTE authenticated + service_role; aceeași semantică (bucățile unui original spart)
CREATE FUNCTION public.ofertare_doc_are_bucati(p_licitatie_id bigint, p_doc_id bigint, p_nume text) RETURNS boolean
  LANGUAGE sql STABLE SET search_path TO 'public', 'pg_temp' AS $corp$
  SELECT EXISTS (
    SELECT 1 FROM ofertare_documente_atribuire b
    WHERE b.licitatie_id = p_licitatie_id
      AND b.id <> p_doc_id
      AND b.nume_original ~ ('^' || regexp_replace(regexp_replace(coalesce(p_nume,''), '\.pdf$', '', 'i'),
                                                   '([.^$*+?()\[\]{}|\\-])', '\\\1', 'g')
                             || ' — p\d+_pag[\d-]+\.pdf$')
  );
$corp$;
REVOKE EXECUTE ON FUNCTION public.ofertare_doc_are_bucati(bigint, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ofertare_doc_are_bucati(bigint, bigint, text) TO authenticated, service_role;
CREATE OR REPLACE VIEW public.v_ofertare_seap_completitudine WITH (security_invoker = on) AS
WITH ess AS (
  SELECT d.licitatie_id,
         count(*) FILTER (WHERE d.tip IN ('fisa_date', 'cs_volum', 'lista_cantitati')) AS esentiale,
         count(*) FILTER (WHERE d.tip = 'cs_volum') AS caiete,
         count(*) FILTER (WHERE d.tip IN ('fisa_date', 'cs_volum', 'lista_cantitati') AND d.status_procesare <> 'procesat') AS esentiale_necitite,
         count(*) FILTER (WHERE d.status_procesare = 'neprocesat') AS necitite_total
  FROM public.ofertare_documente_atribuire d GROUP BY d.licitatie_id
), sf AS (
  SELECT f.licitatie_id,
         count(*) FILTER (WHERE f.stare = 'eroare') AS seap_erori,
         count(*) FILTER (WHERE f.stare = 'identificat') AS seap_in_curs,
         string_agg(f.nume_seap || ' [' || coalesce(f.etapa, '?') || ']', '; ' ORDER BY f.nume_seap) FILTER (WHERE f.stare = 'eroare') AS seap_erori_lista
  FROM public.ofertare_seap_fisiere f GROUP BY f.licitatie_id
), ign AS (
  SELECT d.licitatie_id,
         count(*) AS ignorate_neverificate,
         string_agg(regexp_replace(d.nume_original, '^.*/', ''), '; ' ORDER BY d.id) AS ignorate_lista
  FROM public.ofertare_documente_atribuire d
  WHERE d.status_procesare IN ('ignorat', 'eroare')
    AND d.text_extras IS NULL
    AND d.relevanta_verificata_la IS NULL
    AND d.nume_original !~* '\.(rar|zip|7z|p7s|p7m|xml|log)(\s*\d*)$'
    AND d.nume_original !~ '(^|/)~\$'
    AND NOT public.ofertare_doc_are_bucati(d.licitatie_id, d.id, d.nume_original)   -- originalele sparte în bucăți
  GROUP BY d.licitatie_id
)
SELECT l.id AS licitatie_id,
       (l.c_notice_id IS NOT NULL) AS din_seap,
       CASE WHEN l.c_notice_id IS NULL THEN 'n/a'
            WHEN c.licitatie_id IS NULL OR c.terminat_la IS NULL THEN 'nerulata'
            WHEN c.raport ? 'eroare' THEN 'eroare'
            ELSE 'ok' END AS enumerare,
       c.terminat_la AS enumerare_la,
       (c.raport->>'seap')::int AS seap_total,
       coalesce(sf.seap_erori, 0) AS seap_erori,
       coalesce(sf.seap_in_curs, 0) AS seap_in_curs,
       sf.seap_erori_lista,
       coalesce(e.esentiale, 0) AS esentiale,
       coalesce(e.caiete, 0) AS caiete,
       coalesce(e.esentiale_necitite, 0) AS esentiale_necitite,
       coalesce(e.necitite_total, 0) AS necitite_total,
       CASE
         WHEN l.c_notice_id IS NOT NULL AND (c.licitatie_id IS NULL OR c.terminat_la IS NULL)
           THEN 'nu putem verifica completitudinea: documentația din SEAP nu a fost încă enumerată'
         WHEN l.c_notice_id IS NOT NULL AND c.raport ? 'eroare'
           THEN 'nu putem verifica completitudinea: enumerarea SEAP a eșuat (' || left(c.raport->>'eroare', 120) || ')'
         WHEN coalesce(sf.seap_erori, 0) > 0
           THEN sf.seap_erori || ' fișier(e) din SEAP nerecuperate: ' || left(sf.seap_erori_lista, 300)
         WHEN coalesce(sf.seap_in_curs, 0) > 0
           THEN sf.seap_in_curs || ' fișier(e) din SEAP încă în curs de aducere'
         WHEN coalesce(e.caiete, 0) = 0
           THEN 'niciun caiet de sarcini / volum de proiect identificat în documentație'
         WHEN coalesce(e.esentiale_necitite, 0) > 0
           THEN e.esentiale_necitite || ' document(e) esențiale (fișa de date, caiete/PT, liste de cantități) necitite sau citite parțial'
         WHEN coalesce(g.ignorate_neverificate, 0) > 0
           THEN g.ignorate_neverificate || ' document(e) necitite automat, fără bifa unui om (consultat / nerelevant): ' || left(g.ignorate_lista, 300)
       END AS blocaj,
       coalesce(g.ignorate_neverificate, 0) AS ignorate_neverificate,
       g.ignorate_lista
FROM public.ofertare_licitatii l
LEFT JOIN public.ofertare_seap_cereri c ON c.licitatie_id = l.id
LEFT JOIN sf ON sf.licitatie_id = l.id
LEFT JOIN ess e ON e.licitatie_id = l.id
LEFT JOIN ign g ON g.licitatie_id = l.id;
REVOKE ALL ON public.v_ofertare_seap_completitudine FROM PUBLIC, anon;
GRANT SELECT ON public.v_ofertare_seap_completitudine TO authenticated, service_role;

-- scenariile #11 (fiecare licitație are un caiet citit, ca blocajul să vină doar din ce testăm; 1 = fără SEAP → enumerare n/a)
INSERT INTO public.ofertare_licitatii (id, c_notice_id) SELECT g, NULL FROM generate_series(1, 12) g;
INSERT INTO public.ofertare_documente_atribuire (licitatie_id, nume_original, tip, status_procesare, text_extras)
  SELECT g, 'Caiet de sarcini.pdf', 'cs_volum', 'procesat', 'text' FROM generate_series(1, 12) g;
INSERT INTO public.ofertare_documente_atribuire (licitatie_id, nume_original, tip, status_procesare, eroare, relevanta_verificata_la) VALUES
  (1,  'PT.zip', 'alta', 'ignorat', 'non-PDF - ramane ca fisier (docx/xls/dwg se parseaza in M2)', NULL),           -- vechi, nedespachetat → blocaj
  (2,  'Raspuns.rar', 'alta', 'ignorat', '📦 Arhivă despachetată pe Terra: 3 fișiere noi în platformă', NULL),        -- rezolvat
  (3,  'Doc.rar', 'alta', 'ignorat', 'Arhivă adusă pe Terra: 41 fișiere în platformă.', NULL),                       -- rezolvat (drumul SEAP)
  (4,  'Liste cantitati (fara valori).zip', 'alta', 'ignorat', 'non-PDF - ramane ca fisier', NULL),                  -- rezolvat prin evidența SEAP 'ok'
  (5,  'X.rar', 'alta', 'eroare', 'Despachetare RESPINSĂ de controalele de siguranță: cale nesigură', now()),       -- bifa omului → rezolvat
  (6,  'Caiet.pdf.p7s', 'alta', 'ignorat', 'Semnătura electronică nu s-a putut desface (DER trunchiat): fișierul a rămas ca atare', NULL),  -- ign
  (7,  'Formular.pdf.p7m', 'alta', 'ignorat', 'Doar semnătura electronică (detașată, fără conținut): documentul semnat e alt fișier.', NULL), -- nimic
  (8,  'A.zip.p7s', 'alta', 'eroare', 'Despachetare eșuată (semnătura CMS .p7s/.p7m): DER trunchiat', NULL),        -- arh (nu ign)
  (9,  'In curs.zip', 'alta', 'neprocesat', NULL, NULL),                                                             -- arh (în curs)
  (10, 'Anexa.docx', 'alta', 'ignorat', 'non-PDF', NULL),                                                            -- ign, ca înainte
  (11, 'Placeholder.rar', 'alta', 'ignorat', 'Aparut nou in SEAP, dar nu a putut fi adus automat - urca-l din "Urca fisiere".', NULL), -- arh
  (12, 'Raspuns (#5)/inner.zip', 'alta', 'eroare', 'Despachetare manuală necesară: arhivă imbricată pe nivelul 3', NULL);           -- arh
UPDATE public.ofertare_documente_atribuire SET fisier_path = licitatie_id || '/atribuire/neincarcat/x' WHERE nume_original = 'Placeholder.rar';
INSERT INTO public.ofertare_seap_fisiere (licitatie_id, nume_seap, cheie, stare) VALUES (4, 'Liste cantitati (fara valori).zip', 'listecantitatifaravalori.zip', 'ok');
CREATE SCHEMA supabase_migrations; CREATE TABLE supabase_migrations.schema_migrations (version text PRIMARY KEY, statements text[], name text, created_by text, idempotency_key text, rollback text[]);
SQL
M0="$(q "SELECT md5(pg_get_viewdef('public.v_ofertare_seap_completitudine'::regclass, true))")"
[ "$M0" = 52cf46a83f97f6321225d7f7a41300ea ] || esec "schelet: md5 view $M0 ≠ live 52cf46a8… (scheletul nu reproduce producția)"
REF="$(ca service_role "$BLOC")"
ok "0. schelet = definiția live (md5 52cf46a8…); blocaje de referință: $REF"
# înainte: nicio arhivă / semnătură nu blochează; doar Anexa.docx (10)
[ "$(ca service_role "SELECT string_agg(licitatie_id::text, ',' ORDER BY licitatie_id) FROM v_ofertare_seap_completitudine WHERE blocaj IS NOT NULL")" = 10 ] || esec "0. referința neașteptată: $REF"

# ── 1. fără runner ──
if "${PSQL[@]}" -d "$BAZA" -f "$MIGRARE" >/tmp/compl_arh_1.out 2>&1; then esec "1. migrarea a mers fără runner"; fi
grep -q "garda de livrare" /tmp/compl_arh_1.out || esec "1. alt motiv de refuz: $(tail -2 /tmp/compl_arh_1.out)"
[ "$(q "SELECT md5(pg_get_viewdef('public.v_ofertare_seap_completitudine'::regclass, true))")" = "$M0" ] || esec "1. view-ul s-a schimbat"
ok "1. fără runner → garda refuză, nimic schimbat"

# ── 2. livrare prin runner ──
SHA="$(sha256sum "$MIGRARE" | cut -d' ' -f1)"
SIS="$(q "SELECT system_identifier FROM pg_control_system()")"
RC=0; PSQL_BIN="$PG_BIN/psql" bash "$RADACINA/scripts/livrare_migrare.sh" --migrare "$MIGRARE" --sha256 "$SHA" --versiune 20261008010000 \
  --tinta-db "$BAZA" --tinta-sistem "$SIS" --tinta-host 127.0.0.1 --tinta-port "$PORT" --user postgres >/tmp/compl_arh_runner.out 2>&1 || RC=$?
[ "$RC" = 0 ] || { tail -15 /tmp/compl_arh_runner.out >&2; esec "2. runner cod $RC"; }
ok "2. runner: cod 0 (APLICAT + ÎNREGISTRAT)"
gate_0e "după livrare"
echo "     md5 nou: $(q "SELECT md5(pg_get_viewdef('public.v_ofertare_seap_completitudine'::regclass, true))")"
b() { ca authenticated "SELECT coalesce(blocaj, '-') FROM v_ofertare_seap_completitudine WHERE licitatie_id = $1"; }
n() { ca authenticated "SELECT arhive_nerezolvate || '/' || ignorate_neverificate FROM v_ofertare_seap_completitudine WHERE licitatie_id = $1"; }
case "$(b 1)" in "1 arhivă(e) nedespachetate"*"PT.zip [ignorat]"*) ok "2. lic 1: arhivă veche nedespachetată → blocaj";; *) esec "2. lic 1: $(b 1)";; esac
for i in 2 3 4 5 7; do [ "$(b $i)" = - ] || esec "2. lic $i ar trebui fără blocaj: $(b $i)"; done
ok "2. lic 2–5, 7: despachetată / adusă pe Terra / evidență SEAP ok / bifa omului / semnătură detașată → fără blocaj"
case "$(b 6)" in "1 document(e) necitite automat"*"Caiet.pdf.p7s"*) ok "2. lic 6: semnătură nedesfăcută → blocaj (necitit, fără bifă)";; *) esec "2. lic 6: $(b 6)";; esac
[ "$(n 8)" = 1/0 ] || esec "2. lic 8: arhivă semnată eșuată trebuie numărată o dată, la arhive ($(n 8))"
for i in 8 9 11 12; do case "$(b $i)" in "1 arhivă(e) nedespachetate"*) ;; *) esec "2. lic $i: $(b $i)";; esac; done
ok "2. lic 8, 9, 11, 12: semnătură CMS eșuată / în curs / placeholder neadus / manuală → blocaj la arhive (o singură dată)"
[ "$(b 10)" = "1 document(e) necitite automat, fără bifa unui om (consultat / nerelevant): Anexa.docx" ] || esec "2. lic 10 s-a schimbat: $(b 10)"
ok "2. lic 10 (fără arhive): blocajul identic cu cel de dinainte"
case "$(ca anon "SELECT count(*) FROM v_ofertare_seap_completitudine")" in *"permission denied"*) ok "2. anon refuzat";; *) esec "2. anon citește view-ul";; esac

# ── 3. reaplicare ──
RC=0; PSQL_BIN="$PG_BIN/psql" bash "$RADACINA/scripts/livrare_migrare.sh" --migrare "$MIGRARE" --sha256 "$SHA" --versiune 20261008010001 \
  --tinta-db "$BAZA" --tinta-sistem "$SIS" --tinta-host 127.0.0.1 --tinta-port "$PORT" --user postgres >/tmp/compl_arh_runner2.out 2>&1 || RC=$?
[ "$RC" != 0 ] || esec "3. reaplicarea a trecut"
ok "3. reaplicare refuzată (cod $RC)"

# ── 4. revenire ──
if "${PSQL[@]}" -d "$BAZA" -1 -f "$ROLLBACK" >/tmp/compl_arh_4.out 2>&1; then esec "4. revenirea nearmată a mers"; fi
grep -q "nearmată" /tmp/compl_arh_4.out || esec "4. alt motiv: $(tail -2 /tmp/compl_arh_4.out)"
ok "4. revenire nearmată → refuz"
"${PSQL[@]}" -d "$BAZA" >/dev/null <<SQL || esec "4. revenirea armată a eșuat"
BEGIN;
SELECT set_config('gazpet.revenire_20261020a', 'COMPLETITUDINE_FARA_ARHIVE:' || txid_current(), true) \g /dev/null
\i $ROLLBACK
COMMIT;
SQL
[ "$(ca service_role "$BLOC")" = "$REF" ] || esec "4. blocajele după revenire ≠ referința: $(ca service_role "$BLOC")"
[ "$(ca service_role "SELECT sum(arhive_nerezolvate)::text || coalesce(max(arhive_lista), '-') FROM v_ofertare_seap_completitudine")" = "0-" ] || esec "4. coloanele noi nu sunt neutre"
ok "4. revenire armată → semantica veche (blocaje identice cu referința), coloanele noi neutre"
echo "PASS"
