-- [CTC] F1 — Cărți Tehnice ale Construcției (spec: claude_docs.spec_modul_ctc_carti_tehnice, claude_context #653).
-- Decizii Răzvan 30.09.2026: Q1 A+C (schelet Transgaz generic acum, pozițiile reale extrase ulterior din cărțile
-- de pe NAS) · Q2 B (O SINGURĂ carte pe proiect) · Q3 B (poziție atașabilă din arhiva comenzilor furnizor, prin
-- referință, fără re-upload) · Q4 A (bucket ctc-documente, 50 MB/fișier, doar PDF — imaginile se convertesc
-- client-side, decizia „TOTUL PDF").
-- Decizie Răzvan 30.09.2026 (după analiza cărților STANCEȘTI / TIGVENI / Râul Doamnei + 3 borderouri Transgaz):
-- cărțile reale sunt cronologice pe TRONSOANE (FOD, mal drept, mal stâng, Dn400/Dn500) → varianta A: coloane
-- ctc_carti.tronsoane, ctc_template_pozitii.repetabil, ctc_documente_carte.tronson; template Transgaz v2 din cărți reale.
-- Acces: profiles.can_access_ctc OR profiles.is_owner (ca în spec). Ștergerea unei cărți: doar owner.
-- Tabela veche ctc_documente (goală, legată de comenzi) NU se atinge.
-- Obiecte noi: 4 tabele + 1 view (security_invoker) + bucket + policies. Fără funcții, fără edge functions.

-- ─── 1. Template-uri per beneficiar ─────────────────────────────
CREATE TABLE public.ctc_templates (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiar_nume text NOT NULL,
  denumire        text NOT NULL,
  activ           boolean NOT NULL DEFAULT true,
  observatii      text,
  created_by      uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.ctc_templates IS '[CTC] Template carte tehnică per beneficiar (Transgaz, Distrigaz, Delgaz…). Checklist-ul stă în ctc_template_pozitii.';

CREATE TABLE public.ctc_template_pozitii (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id       bigint NOT NULL REFERENCES public.ctc_templates(id) ON DELETE CASCADE,
  categorie         text NOT NULL,
  denumire_document text NOT NULL,
  ordine            int  NOT NULL,
  obligatoriu       boolean NOT NULL DEFAULT true,
  repetabil         boolean NOT NULL DEFAULT false,  -- true = se clonează pe fiecare tronson/probă al cărții (FOD, mal drept, mal stâng, Dn400…)
  observatii        text,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ctc_template_pozitii_tpl_idx ON public.ctc_template_pozitii (template_id, ordine);
COMMENT ON TABLE public.ctc_template_pozitii IS '[CTC] Pozițiile (documentele cerute) ale unui template, în ordinea din borderou.';

-- ─── 2. Cărțile ─────────────────────────────────────────────────
CREATE TABLE public.ctc_carti (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proiect_id           bigint REFERENCES public.executie_proiecte(id) ON DELETE SET NULL,
  contract_id          bigint REFERENCES public.contracte_terti(id)   ON DELETE SET NULL,
  template_id          bigint REFERENCES public.ctc_templates(id)     ON DELETE SET NULL,
  beneficiar_nume      text,
  denumire_obiectiv    text NOT NULL,
  numar_contract       text,
  data_contract        date,
  localitate           text,
  judet                text,
  tronsoane            text[] NOT NULL DEFAULT '{}',   -- unitățile de repetare alese la creare (ex. {FOD,Mal drept,Mal stâng}); pozițiile repetabile se clonează pe ele
  status               text NOT NULL DEFAULT 'in_lucru' CHECK (status IN ('in_lucru','completa','predata')),
  borderou_path        text,
  borderou_generat_at  timestamptz,
  pdf_final_path       text,          -- F2 (PDF unificat, Edge Function)
  pdf_final_generat_at timestamptz,   -- F2
  predat_la            date,
  predat_catre         text,
  pv_predare_path      text,
  observatii           text,
  created_by           uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ctc_carti_proiect_unic UNIQUE (proiect_id)   -- Q2 B: o singură carte pe proiect (NULL = lucrare fără proiect în Execuție)
);
COMMENT ON TABLE public.ctc_carti IS '[CTC] Cartea Tehnică a Construcției: dosarul de conformitate predat beneficiarului la recepție. 1 carte / proiect.';

-- ─── 3. Documentele unei cărți (checklist-ul concret) ───────────
CREATE TABLE public.ctc_documente_carte (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carte_id            bigint NOT NULL REFERENCES public.ctc_carti(id) ON DELETE CASCADE,
  template_pozitie_id bigint REFERENCES public.ctc_template_pozitii(id) ON DELETE SET NULL,
  tronson             text,            -- NULL = poziție generală; altfel tronsonul/proba pe care se repetă (vezi ctc_carti.tronsoane)
  categorie           text NOT NULL,
  denumire_document   text NOT NULL,
  nr_pozitie          int,             -- numărul din borderou (se recalculează la generare)
  ordine              int NOT NULL,
  obligatoriu         boolean NOT NULL DEFAULT true,
  status              text NOT NULL DEFAULT 'lipsa' CHECK (status IN ('lipsa','incarcat','verificat','na')),
  -- fișierul: fie urcat în ctc-documente, fie referință la un document din arhiva comenzilor (Q3 B)
  sursa               text NOT NULL DEFAULT 'upload' CHECK (sursa IN ('upload','arhiva_comenzi')),
  fisier_bucket       text NOT NULL DEFAULT 'ctc-documente' CHECK (fisier_bucket IN ('ctc-documente','comenzi-furnizor')),
  fisier_path         text,
  fisier_nume         text,
  fisier_size_bytes   bigint,
  cfd_id              bigint REFERENCES public.comenzi_furnizor_documente(id) ON DELETE SET NULL,
  nr_pagini           int CHECK (nr_pagini IS NULL OR nr_pagini > 0),
  nr_pagina_start     int,
  nr_pagina_end       int,
  observatii          text,
  uploadat_de         uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  uploadat_la         timestamptz,
  verificat_de        uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  verificat_la        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ctc_doc_sursa_coerenta CHECK (
    (sursa = 'upload' AND fisier_bucket = 'ctc-documente')
    OR (sursa = 'arhiva_comenzi' AND fisier_bucket = 'comenzi-furnizor')
  )
);
CREATE INDEX ctc_documente_carte_carte_idx ON public.ctc_documente_carte (carte_id, ordine);
CREATE INDEX ctc_documente_carte_tronson_idx ON public.ctc_documente_carte (carte_id, tronson);
CREATE INDEX ctc_documente_carte_cfd_idx   ON public.ctc_documente_carte (cfd_id) WHERE cfd_id IS NOT NULL;
COMMENT ON TABLE public.ctc_documente_carte IS '[CTC] Pozițiile concrete ale unei cărți (copiate din template la creare, editabile). Fișier propriu sau referință la comenzi_furnizor_documente.';

-- ─── 4. updated_at ──────────────────────────────────────────────
CREATE TRIGGER ctc_templates_updated_at       BEFORE UPDATE ON public.ctc_templates       FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER ctc_carti_updated_at           BEFORE UPDATE ON public.ctc_carti           FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER ctc_documente_carte_updated_at BEFORE UPDATE ON public.ctc_documente_carte FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─── 5. RLS + GRANT ─────────────────────────────────────────────
ALTER TABLE public.ctc_templates        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ctc_template_pozitii ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ctc_carti            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ctc_documente_carte  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.ctc_templates, public.ctc_template_pozitii, public.ctc_carti, public.ctc_documente_carte FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ctc_templates, public.ctc_template_pozitii, public.ctc_carti, public.ctc_documente_carte TO authenticated;
GRANT ALL ON public.ctc_templates, public.ctc_template_pozitii, public.ctc_carti, public.ctc_documente_carte TO service_role;

-- Acces CTC = can_access_ctc OR is_owner. Ștergerea unei cărți întregi = doar owner.
DO $$
DECLARE t text;
  acces constant text := '(auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)))';
  owner constant text := '(auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.is_owner))';
BEGIN
  FOREACH t IN ARRAY ARRAY['ctc_templates','ctc_template_pozitii','ctc_carti','ctc_documente_carte'] LOOP
    EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING %s', t||'_select', t, acces);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK %s', t||'_insert', t, acces);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING %s WITH CHECK %s', t||'_update', t, acces, acces);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING %s', t||'_delete', t,
                   CASE WHEN t = 'ctc_carti' THEN owner ELSE acces END);
  END LOOP;
END $$;

-- ─── 6. View progres (checklist „47/93") ────────────────────────
CREATE VIEW public.v_ctc_carti_progres WITH (security_invoker = on) AS
SELECT c.id AS carte_id,
       count(d.id)                                                          AS total_pozitii,
       count(d.id) FILTER (WHERE d.status <> 'na')                           AS pozitii_aplicabile,
       count(d.id) FILTER (WHERE d.status IN ('incarcat','verificat'))       AS pozitii_incarcate,
       count(d.id) FILTER (WHERE d.status = 'verificat')                     AS pozitii_verificate,
       count(d.id) FILTER (WHERE d.status = 'lipsa' AND d.obligatoriu)       AS obligatorii_lipsa,
       coalesce(sum(d.nr_pagini) FILTER (WHERE d.status IN ('incarcat','verificat')), 0) AS total_pagini
FROM public.ctc_carti c
LEFT JOIN public.ctc_documente_carte d ON d.carte_id = c.id
GROUP BY c.id;
REVOKE ALL ON public.v_ctc_carti_progres FROM anon;
GRANT SELECT ON public.v_ctc_carti_progres TO authenticated, service_role;

-- ─── 7. Bucket ctc-documente (privat, 50 MB, doar PDF) ──────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('ctc-documente', 'ctc-documente', false, 52428800, ARRAY['application/pdf'])
ON CONFLICT (id) DO NOTHING;

CREATE POLICY ctc_storage_select ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));
CREATE POLICY ctc_storage_insert ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));
CREATE POLICY ctc_storage_update ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));
CREATE POLICY ctc_storage_delete ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));

-- ─── 8. Seed: template Transgaz v2 (din cărțile reale STANCEȘTI / TIGVENI / Râul Doamnei + borderouri) ──
-- 58 poziții; 20 repetabile (execuție pe tronson + probe). Andruț le poate edita din UI.
WITH t AS (
  INSERT INTO public.ctc_templates (beneficiar_nume, denumire, observatii, created_by)
  VALUES ('Transgaz', 'Transgaz — conductă transport (v2, din cărți reale 2024–2026)',
          'Construit din cărțile STANCEȘTI, TIGVENI, Râul Doamnei și borderourile Bistrița–Viișoara / Vrăjitoarea / Valea Tapului. Secțiunile C și D se repetă pe tronson/probă.', NULL)
  RETURNING id
)
INSERT INTO public.ctc_template_pozitii (template_id, categorie, denumire_document, ordine, obligatoriu, repetabil, observatii)
SELECT t.id, v.categorie, v.denumire, v.ordine, v.obligatoriu, v.repetabil, v.obs
FROM t, (VALUES
  -- A. Documentație generală
  ('Autorizații & avize',           'Autorizație de construire',                                                   10, true,  false, NULL),
  ('Autorizații & avize',           'Comunicare începere execuție (F.14) către ISC / primărie',                    20, true,  false, NULL),
  ('Autorizații & avize',           'Aviz ISC la Programul de control al calității',                               30, true,  false, 'Fixează fazele determinante cerute de ISC'),
  ('Program control calitate',      'Program pentru controlul calității (PCCVI) — faze determinante',              40, true,  false, NULL),
  ('Autorizații & avize',           'Ordin de începere (+ sistare / reîncepere, dacă e cazul)',                    50, true,  false, NULL),
  ('Autorizații & avize',           'PV predare-primire amplasament și borne de reper',                            60, true,  false, NULL),
  ('Autorizații & avize',           'PV trasare lucrări',                                                          70, true,  false, NULL),
  ('Certificări firmă/personal',    'Certificate ISO 9001 / 14001 / 45001 (+ anexa de menținere)',                110, true,  false, NULL),
  ('Certificări firmă/personal',    'Autorizații ANRE (tip ET, EPI)',                                             120, true,  false, NULL),
  ('Certificări firmă/personal',    'Autorizație laborator NDT (ISC) + autorizații ISCIR pe metode',              130, true,  false, 'Când NDT e făcut de laborator extern'),
  ('Decizii numire personal',       'Decizie numire Responsabil Tehnic cu Execuția (RTE)',                        210, true,  false, NULL),
  ('Certificări firmă/personal',    'Autorizație ISC + legitimație RTE',                                          220, true,  false, NULL),
  ('Decizii numire personal',       'Decizie numire Responsabil Tehnic cu Sudura (RTS)',                          230, true,  false, NULL),
  ('Certificări firmă/personal',    'Certificat RTS (atestat / examinare vizuală nivel 2 / IWE)',                 240, true,  false, NULL),
  ('Decizii numire personal',       'Decizie numire manager proiect / șef de șantier',                            250, true,  false, NULL),
  ('Decizii numire personal',       'Decizie numire responsabil CTC / CQ',                                        260, true,  false, NULL),
  ('Decizii numire personal',       'Decizie numire operator examinare vizuală nivel 2 + certificare',            270, false, false, NULL),
  ('Sudură',                        'Lista WPS & WPQR',                                                           310, true,  false, NULL),
  ('Sudură',                        'WPS — specificația procedurii de sudare',                                    320, true,  false, NULL),
  ('Sudură',                        'WPQR — certificat + raport de încercare',                                    330, true,  false, NULL),
  ('Sudură',                        'Tabel sudori autorizați',                                                    340, true,  false, NULL),
  ('Sudură',                        'Certificate de calificare sudori (ISO 9606-1)',                              350, true,  false, 'Unul pe sudor'),
  ('Calibrări AMC',                 'Certificate calibrare / verificare aparate (manometru înregistrator, izotest / defectoscop)', 360, true, false, NULL),
  -- B. Materiale: PVRC + certificate furnizor (PVRC-ul stă înaintea certificatelor)
  ('Certificate materiale + PVRC',  'Țeavă de linie — PVRC + certificate inspecție 3.1 + declarații',             410, true,  false, NULL),
  ('Certificate materiale + PVRC',  'PV custodie materiale livrate de beneficiar',                                415, false, false, 'Doar când țeava / curbele vin de la beneficiar'),
  ('Certificate materiale + PVRC',  'Curbe / reducții — PVRC + certificate',                                      420, true,  false, NULL),
  ('Certificate materiale + PVRC',  'Protecție mecanică / izolație țeavă (aplicată în stație) — PVRC + certificat + listă lot', 430, true, false, NULL),
  ('Certificate materiale + PVRC',  'Benzi PE / manșoane termocontractabile — PVRC + certificate',                440, true,  false, NULL),
  ('Certificate materiale + PVRC',  'Material bicomponent A+B — PVRC + certificate de analiză',                   450, true,  false, NULL),
  ('Certificate materiale + PVRC',  'Electrozi / material de adaos — PVRC + certificate',                         460, true,  false, NULL),
  ('Certificate materiale + PVRC',  'Fitinguri speciale (refulare-egalizare, flanșă multifuncțională) — PVRC + certificate componente', 470, false, false, 'Subansamblurile de atelier au și raport de trasabilitate + PV probă'),
  ('Certificate materiale + PVRC',  'Robinete — PVRC + certificate / DoC',                                        480, false, false, NULL),
  ('Certificate materiale + PVRC',  'Weldolet / flanșe — PVRC + certificate',                                     490, false, false, NULL),
  ('Certificate materiale + PVRC',  'Obturator / dop gonflabil — PVRC + certificate',                             495, false, false, NULL),
  ('Rapoarte & buletine măsurare',  'Raport verificare izolație țeavă în stație + buletine măsurare (grosime, continuitate)', 500, false, false, NULL),
  -- C. Execuție — se repetă pe fiecare tronson (FOD / mal drept / mal stâng / Dn400 / Dn500)
  ('PVLA lucrări ascunse',          'PVLA culoar de lucru / decopertare strat vegetal',                           610, true,  true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA săpătură șanț',                                                         620, true,  true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA pat de pământ mărunțit',                                                630, true,  true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA montaj fir conductă (sudare pe rampă / în șanț)',                       640, true,  true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA curățare suprafețe metalice (sablare) — suduri / curbe',                650, true,  true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA izolare suduri / curbe',                                                660, true,  true,  NULL),
  ('Rapoarte & buletine măsurare',  'PV verificare izolație (defectoscop cu scânteie)',                           670, true,  true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA protecție mecanică zonă suduri',                                        680, false, true,  'Tronsoane cu foraj / protecție mecanică'),
  ('Rapoarte & buletine măsurare',  'PV verificare protecție mecanică',                                           685, false, true,  NULL),
  ('PVLA lucrări ascunse',          'PVLA tragere în gaura forată (FOD)',                                         690, false, true,  'Doar tronsonul FOD'),
  ('PVLA lucrări ascunse',          'PVLA astupare șanț',                                                         700, false, true,  'Tronsoane în șanț'),
  ('Sudură',                        'Tabel execuție suduri',                                                      710, true,  true,  NULL),
  ('Sudură',                        'Buletin examinare vizuală suduri',                                           720, true,  true,  NULL),
  ('Sudură',                        'Buletine control NDT suduri (UT / PT / RT)',                                 730, true,  true,  NULL),
  ('As-Built / scheme',             'Schemă izometrică / red mark',                                               740, true,  true,  NULL),
  ('As-Built / scheme',             'Protocol / raport traseu foraj dirijat (FOD)',                               750, false, true,  'Doar tronsonul FOD'),
  -- D. Probe de presiune — se repetă pe fiecare probă (intermediară / rezistență / etanșeitate)
  ('Faze determinante',             'PV fază determinantă (cu lista documentelor-suport)',                        810, true,  true,  NULL),
  ('Probe presiune',                'PV probă de presiune',                                                       820, true,  true,  NULL),
  ('Probe presiune',                'Diagramă înregistrator presiune / temperatură',                              830, true,  true,  NULL),
  ('Probe presiune',                'PV golire / pistonare conductă',                                             840, false, true,  NULL),
  -- E. As-Built & recepție
  ('As-Built / scheme',             'Plan as-built / traseu executat',                                            910, true,  false, NULL),
  ('As-Built / scheme',             'Profil longitudinal',                                                        920, false, false, NULL),
  ('Recepție',                      'PV recepție la terminarea lucrărilor',                                       930, true,  false, NULL)
) AS v(categorie, denumire, ordine, obligatoriu, repetabil, obs);
