-- P0a — Source Pack v1 → Registru cerințe (Ofertare). Doar schemă + RPC + triggere + RLS.
-- Plan: docs/as-is/ofertare + PLAN_TEHNIC_P0_v2 (23.09.2026). Fără UI, fără worker (P0b/P0c).
--
-- Ce face:
--   1. ofertare_source_pack — pack-ul integral, imuabil (trigger, nu doar RLS: service_role sare peste RLS).
--   2. ofertare_source_pack_importuri — istoric append-only al fiecărei selecții umane de import.
--   3. ofertare_cerinte — 8 coloane nullable de proveniență + CHECK cand_se_prezinta extins + trigger
--      care protejează proveniența (textul rămâne editabil, dar ștampilat).
--   4. fn_ofertare_source_pack_preview (SECURITY INVOKER, STABLE, nu scrie) și
--      fn_ofertare_source_pack_import (SECURITY DEFINER, actor = auth.uid(), owner/responsabil).
--   5. v_ofertare_source_pack_nereusite (security_invoker).
-- Semantică (grounding): validatorul demonstrează literal doar sursa_pasaj (excerptul) + locatorul.
-- text_cerinta este cerința STRUCTURATĂ (grounded), nu „verbatim verificat”. UI/gate-urile păstrează diferența.

-- ───────────────────────── 1. ofertare_source_pack ─────────────────────────
CREATE TABLE IF NOT EXISTS public.ofertare_source_pack (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  licitatie_id   bigint NOT NULL REFERENCES public.ofertare_licitatii(id) ON DELETE CASCADE,
  stamp          text,
  fisier         text,
  pack_hash      text NOT NULL UNIQUE CHECK (pack_hash ~ '^[0-9a-f]{64}$'),
  sursa          text NOT NULL DEFAULT 'cli' CHECK (sursa IN ('cli')),
  model          text,
  cost_usd       numeric,
  ture           integer,
  durata_s       integer,
  pack           jsonb NOT NULL,
  validare       jsonb,
  nr_cerinte     integer,
  nr_nereusite   integer,
  nr_erate       integer,
  -- preview-ul NU schimbă starea; 'importat' doar când toate cerințele importabile sunt în registru
  stare          text NOT NULL DEFAULT 'primit' CHECK (stare IN ('primit','importat_partial','importat','respins')),
  ultim_import_la timestamptz,
  nota           text,
  creat_la       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ofertare_source_pack_identitate_chk CHECK ((pack #>> '{licitatie,licitatie_id}')::bigint = licitatie_id)
);
COMMENT ON TABLE public.ofertare_source_pack IS 'Source Pack v1 (gazpet.source_pack/v1) produs de CLI pe NAS și validat fără AI. Conținut EXTERN: se afișează, nu se execută. Imuabil după INSERT (trigger).';
COMMENT ON COLUMN public.ofertare_source_pack.pack IS 'Pack-ul integral. pack.documente[].sha256 = hash-ul fișierului de pe NAS așa cum a fost citit; NU afirmă identitate de bytes cu storage-ul ERP.';

-- Imutabilitate reală (RLS nu oprește service_role): după INSERT, identitatea pack-ului nu se mai schimbă.
CREATE OR REPLACE FUNCTION public.fn_ofertare_source_pack_imutabil()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'ofertare_source_pack: ștergerea nu e permisă (istoric); se marchează stare=respins';
  END IF;
  IF NEW.pack IS DISTINCT FROM OLD.pack OR NEW.pack_hash IS DISTINCT FROM OLD.pack_hash
     OR NEW.licitatie_id IS DISTINCT FROM OLD.licitatie_id OR NEW.sursa IS DISTINCT FROM OLD.sursa
     OR NEW.stamp IS DISTINCT FROM OLD.stamp OR NEW.fisier IS DISTINCT FROM OLD.fisier
     OR NEW.validare IS DISTINCT FROM OLD.validare OR NEW.creat_la IS DISTINCT FROM OLD.creat_la
     OR NEW.model IS DISTINCT FROM OLD.model OR NEW.cost_usd IS DISTINCT FROM OLD.cost_usd
     OR NEW.ture IS DISTINCT FROM OLD.ture OR NEW.durata_s IS DISTINCT FROM OLD.durata_s
     OR NEW.nr_cerinte IS DISTINCT FROM OLD.nr_cerinte OR NEW.nr_nereusite IS DISTINCT FROM OLD.nr_nereusite
     OR NEW.nr_erate IS DISTINCT FROM OLD.nr_erate THEN
    RAISE EXCEPTION 'ofertare_source_pack: pack-ul e imuabil; doar stare/ultim_import_la/nota se pot schimba';
  END IF;
  RETURN NEW;
END $fn$;
REVOKE ALL ON FUNCTION public.fn_ofertare_source_pack_imutabil() FROM PUBLIC, anon;
DROP TRIGGER IF EXISTS trg_ofertare_source_pack_imutabil ON public.ofertare_source_pack;
CREATE TRIGGER trg_ofertare_source_pack_imutabil
  BEFORE UPDATE OR DELETE ON public.ofertare_source_pack
  FOR EACH ROW EXECUTE FUNCTION public.fn_ofertare_source_pack_imutabil();

ALTER TABLE public.ofertare_source_pack ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.ofertare_source_pack TO authenticated;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.ofertare_source_pack FROM authenticated;
GRANT SELECT, INSERT, UPDATE ON public.ofertare_source_pack TO service_role;
DROP POLICY IF EXISTS ofertare_source_pack_select ON public.ofertare_source_pack;
CREATE POLICY ofertare_source_pack_select ON public.ofertare_source_pack
  FOR SELECT TO authenticated USING ((SELECT public.fn_are_acces_ofertare()));
-- fără policy INSERT/UPDATE/DELETE pentru authenticated: scrie doar workerul (service_role) și RPC-ul (definer)

-- ───────────────────────── 2. istoric importuri (append-only) ─────────────────────────
CREATE TABLE IF NOT EXISTS public.ofertare_source_pack_importuri (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pack_id    bigint NOT NULL REFERENCES public.ofertare_source_pack(id) ON DELETE RESTRICT,
  actor      uuid NOT NULL REFERENCES public.profiles(id),
  refs_cerute text[] NOT NULL,
  inserate   bigint[] NOT NULL DEFAULT '{}',   -- id-uri ofertare_cerinte (rollback: DELETE WHERE id = ANY)
  sarite     text[] NOT NULL DEFAULT '{}',     -- deja importate (pack_id, ref)
  nemapate   text[] NOT NULL DEFAULT '{}',     -- document negăsit în ERP
  refuzate   text[] NOT NULL DEFAULT '{}',     -- ref inexistent în pack
  creat_la   timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.ofertare_source_pack_importuri IS 'Fiecare apăsare umană „Importă” = un rând. Append-only (trigger). Al doilea import nu șterge urma primului.';
CREATE OR REPLACE FUNCTION public.fn_ofertare_source_pack_importuri_ro()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
BEGIN
  RAISE EXCEPTION 'ofertare_source_pack_importuri: append-only (fără UPDATE/DELETE)';
END $fn$;
REVOKE ALL ON FUNCTION public.fn_ofertare_source_pack_importuri_ro() FROM PUBLIC, anon;
DROP TRIGGER IF EXISTS trg_ofertare_source_pack_importuri_ro ON public.ofertare_source_pack_importuri;
CREATE TRIGGER trg_ofertare_source_pack_importuri_ro
  BEFORE UPDATE OR DELETE ON public.ofertare_source_pack_importuri
  FOR EACH ROW EXECUTE FUNCTION public.fn_ofertare_source_pack_importuri_ro();
ALTER TABLE public.ofertare_source_pack_importuri ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.ofertare_source_pack_importuri TO authenticated;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.ofertare_source_pack_importuri FROM authenticated;
GRANT SELECT, INSERT ON public.ofertare_source_pack_importuri TO service_role;
DROP POLICY IF EXISTS ofertare_source_pack_importuri_select ON public.ofertare_source_pack_importuri;
CREATE POLICY ofertare_source_pack_importuri_select ON public.ofertare_source_pack_importuri
  FOR SELECT TO authenticated USING ((SELECT public.fn_are_acces_ofertare()));

-- ───────────────────────── 3. ofertare_cerinte — proveniență din pack ─────────────────────────
ALTER TABLE public.ofertare_cerinte
  ADD COLUMN IF NOT EXISTS sursa_pack_id      bigint REFERENCES public.ofertare_source_pack(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS sursa_ref          text,
  ADD COLUMN IF NOT EXISTS locator_verificat  text CHECK (locator_verificat IN ('pagina','document')),
  ADD COLUMN IF NOT EXISTS pagina_declarata   integer,
  ADD COLUMN IF NOT EXISTS incertitudine      text CHECK (incertitudine IN ('sigur','probabil','neclar')),
  ADD COLUMN IF NOT EXISTS sursa_mapare       text CHECK (sursa_mapare IN ('id_context','seap_cod','nume_exact','nume_normalizat','niciuna')),
  ADD COLUMN IF NOT EXISTS text_editat_la     timestamptz,
  ADD COLUMN IF NOT EXISTS text_editat_de     uuid REFERENCES public.profiles(id);
COMMENT ON COLUMN public.ofertare_cerinte.sursa_pack_id IS 'Rând importat din Source Pack. Proveniența (sursa_pasaj/pagina/locator_verificat/ref/mapare) e blocată de trigger; text_cerinta rămâne editabil dar ștampilat (text_editat_*). Originalul e mereu în ofertare_source_pack.pack.';
COMMENT ON COLUMN public.ofertare_cerinte.locator_verificat IS 'Verdictul validatorului FĂRĂ AI pe excerpt (sursa_pasaj): pagina = găsit pe pagina declarată; document = găsit în document, pagina corectată (pagina_declarata = ce a afirmat modelul). NULL = rând care nu a trecut prin validator.';
COMMENT ON COLUMN public.ofertare_cerinte.sursa_mapare IS 'Cum s-a legat nume_fisier din pack de ofertare_documente_atribuire: id_context > seap_cod > nume_exact > nume_normalizat. Nu e identitate de bytes.';
CREATE UNIQUE INDEX IF NOT EXISTS ofertare_cerinte_pack_ref_unic
  ON public.ofertare_cerinte (sursa_pack_id, sursa_ref) WHERE sursa_pack_id IS NOT NULL;

-- cand_se_prezinta: la_solicitare rămâne stare distinctă (nu se mapează la primul_loc); executie = cerință de execuție.
ALTER TABLE public.ofertare_cerinte DROP CONSTRAINT IF EXISTS ofertare_cerinte_cand_se_prezinta_check;
ALTER TABLE public.ofertare_cerinte ADD CONSTRAINT ofertare_cerinte_cand_se_prezinta_check
  CHECK (cand_se_prezinta = ANY (ARRAY['duae','depunere','primul_loc','executie','la_solicitare']));

-- Proveniența unei cerințe din pack nu se editează; sursa_pack_id se poate seta doar din RPC-ul de import.
CREATE OR REPLACE FUNCTION public.fn_ofertare_cerinte_pack_protejeaza()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.sursa_pack_id IS NOT NULL AND COALESCE(current_setting('ofertare.import_pack', true), '') <> 'on' THEN
      RAISE EXCEPTION 'ofertare_cerinte: sursa_pack_id se setează doar prin fn_ofertare_source_pack_import';
    END IF;
    RETURN NEW;
  END IF;
  IF NEW.sursa_pack_id IS DISTINCT FROM OLD.sursa_pack_id THEN
    RAISE EXCEPTION 'ofertare_cerinte: sursa_pack_id nu se schimbă';
  END IF;
  IF OLD.sursa_pack_id IS NOT NULL THEN
    IF NEW.sursa_pasaj IS DISTINCT FROM OLD.sursa_pasaj OR NEW.sursa_pagina IS DISTINCT FROM OLD.sursa_pagina
       OR NEW.pagina_declarata IS DISTINCT FROM OLD.pagina_declarata OR NEW.locator_verificat IS DISTINCT FROM OLD.locator_verificat
       OR NEW.sursa_ref IS DISTINCT FROM OLD.sursa_ref OR NEW.sursa_document_id IS DISTINCT FROM OLD.sursa_document_id
       OR NEW.sursa_mapare IS DISTINCT FROM OLD.sursa_mapare OR NEW.pasaj_verificat IS DISTINCT FROM OLD.pasaj_verificat
       OR NEW.incertitudine IS DISTINCT FROM OLD.incertitudine THEN
      RAISE EXCEPTION 'ofertare_cerinte: câmpurile de proveniență ale unei cerințe din pack nu se editează (originalul e în pack)';
    END IF;
    IF NEW.text_cerinta IS DISTINCT FROM OLD.text_cerinta THEN
      NEW.text_editat_la := now();
      NEW.text_editat_de := auth.uid();
    END IF;
  END IF;
  RETURN NEW;
END $fn$;
REVOKE ALL ON FUNCTION public.fn_ofertare_cerinte_pack_protejeaza() FROM PUBLIC, anon;
DROP TRIGGER IF EXISTS trg_ofertare_cerinte_pack_protejeaza ON public.ofertare_cerinte;
CREATE TRIGGER trg_ofertare_cerinte_pack_protejeaza
  BEFORE INSERT OR UPDATE ON public.ofertare_cerinte
  FOR EACH ROW EXECUTE FUNCTION public.fn_ofertare_cerinte_pack_protejeaza();

-- ───────────────────────── 4. mapare nume_fisier → document ERP ─────────────────────────
-- Întoarce (document_id, sursa_mapare). Ordinea: id din context (pack.documente[].id) > seap_cod > nume exact > nume normalizat.
CREATE OR REPLACE FUNCTION public.fn_ofertare_source_pack_mapeaza_doc(p_licitatie_id bigint, p_nume_fisier text, p_seap_cod text, p_id_context bigint)
RETURNS TABLE (document_id bigint, sursa_mapare text)
LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_baza text := regexp_replace(COALESCE(p_nume_fisier, ''), '^.*/', '');
  v_norm text := regexp_replace(lower(v_baza), '[^a-z0-9]+', '', 'g');
  v_id bigint;
BEGIN
  IF p_id_context IS NOT NULL THEN
    SELECT d.id INTO v_id FROM public.ofertare_documente_atribuire d WHERE d.id = p_id_context AND d.licitatie_id = p_licitatie_id;
    IF v_id IS NOT NULL THEN document_id := v_id; sursa_mapare := 'id_context'; RETURN NEXT; RETURN; END IF;
  END IF;
  IF p_seap_cod IS NOT NULL THEN
    SELECT d.id INTO v_id FROM public.ofertare_documente_atribuire d WHERE d.licitatie_id = p_licitatie_id AND d.seap_cod = p_seap_cod LIMIT 1;
    IF v_id IS NOT NULL THEN document_id := v_id; sursa_mapare := 'seap_cod'; RETURN NEXT; RETURN; END IF;
  END IF;
  SELECT d.id INTO v_id FROM public.ofertare_documente_atribuire d
   WHERE d.licitatie_id = p_licitatie_id AND d.nume_original = v_baza ORDER BY d.id LIMIT 1;
  IF v_id IS NOT NULL THEN document_id := v_id; sursa_mapare := 'nume_exact'; RETURN NEXT; RETURN; END IF;
  SELECT d.id INTO v_id FROM public.ofertare_documente_atribuire d
   WHERE d.licitatie_id = p_licitatie_id AND regexp_replace(lower(d.nume_original), '[^a-z0-9]+', '', 'g') = v_norm ORDER BY d.id LIMIT 1;
  IF v_id IS NOT NULL THEN document_id := v_id; sursa_mapare := 'nume_normalizat'; RETURN NEXT; RETURN; END IF;
  document_id := NULL; sursa_mapare := 'niciuna'; RETURN NEXT;
END $fn$;
REVOKE ALL ON FUNCTION public.fn_ofertare_source_pack_mapeaza_doc(bigint, text, text, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_ofertare_source_pack_mapeaza_doc(bigint, text, text, bigint) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.fn_ofertare_source_pack_cand(p text)
RETURNS text LANGUAGE sql IMMUTABLE AS $fn$
  SELECT CASE p WHEN 'DUAE' THEN 'duae' WHEN 'la_depunere' THEN 'depunere' WHEN 'la_solicitare' THEN 'la_solicitare'
                WHEN 'in_executie' THEN 'executie' ELSE NULL END
$fn$;

-- ───────────────────────── 5. preview (nu scrie, nu schimbă starea) ─────────────────────────
CREATE OR REPLACE FUNCTION public.fn_ofertare_source_pack_preview(p_pack_id bigint, p_prag real DEFAULT 0.45)
RETURNS TABLE (
  ref text, text_grounded text, tip text, cand_se_prezinta text, document_probant text, lot text,
  nume_fisier text, document_id bigint, sursa_mapare text,
  pagina integer, pagina_declarata integer, sectiune text, excerpt_verificat text, locator_verificat text, incertitudine text,
  seamana_cu_id bigint, seamana_cu_similarity real, deja_importat boolean, importabil boolean
)
LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_pack public.ofertare_source_pack%ROWTYPE;
BEGIN
  SELECT * INTO v_pack FROM public.ofertare_source_pack sp WHERE sp.id = p_pack_id;  -- RLS: fn_are_acces_ofertare
  IF v_pack.id IS NULL THEN RAISE EXCEPTION 'pack inexistent sau fără acces'; END IF;
  RETURN QUERY
  WITH c AS (
    SELECT x.value AS j, x.ordinality AS ord FROM jsonb_array_elements(COALESCE(v_pack.pack->'cerinte', '[]'::jsonb)) WITH ORDINALITY x
  ), m AS (
    SELECT c.j, c.ord,
           c.j->>'ref' AS ref,
           c.j#>>'{locator,nume_fisier}' AS nume_fisier,
           d.document_id, d.sursa_mapare
    FROM c
    LEFT JOIN LATERAL (
      SELECT * FROM public.fn_ofertare_source_pack_mapeaza_doc(
        v_pack.licitatie_id, c.j#>>'{locator,nume_fisier}', c.j#>>'{locator,seap_cod}',
        (SELECT (dd->>'id')::bigint FROM jsonb_array_elements(COALESCE(v_pack.pack->'documente','[]'::jsonb)) dd
          WHERE dd->>'nume_fisier' = c.j#>>'{locator,nume_fisier}' LIMIT 1))
    ) d ON true
  )
  SELECT m.ref,
         m.j->>'text',
         m.j->>'tip',
         public.fn_ofertare_source_pack_cand(m.j->>'cand_se_prezinta'),
         m.j->>'document_probant',
         m.j->>'lot',
         m.nume_fisier, m.document_id, m.sursa_mapare,
         COALESCE((m.j#>>'{locator,pagina_validata}')::int, (m.j#>>'{locator,pagina}')::int),
         (m.j#>>'{locator,pagina_declarata}')::int,
         m.j#>>'{locator,sectiune}',
         m.j#>>'{locator,excerpt}',
         m.j#>>'{locator,verificat}',
         m.j->>'incertitudine',
         s.id, s.sim,
         EXISTS (SELECT 1 FROM public.ofertare_cerinte oc WHERE oc.sursa_pack_id = p_pack_id AND oc.sursa_ref = m.ref),
         (m.document_id IS NOT NULL)
  FROM m
  LEFT JOIN LATERAL (
    SELECT oc.id, extensions.similarity(oc.text_cerinta, m.j->>'text') AS sim
    FROM public.ofertare_cerinte oc
    WHERE oc.licitatie_id = v_pack.licitatie_id AND oc.inlocuita_de IS NULL AND oc.duplicat_al IS NULL
      AND extensions.similarity(oc.text_cerinta, m.j->>'text') >= p_prag
    ORDER BY sim DESC, oc.id LIMIT 1
  ) s ON true
  ORDER BY m.ord;
END $fn$;
REVOKE ALL ON FUNCTION public.fn_ofertare_source_pack_preview(bigint, real) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_ofertare_source_pack_preview(bigint, real) TO authenticated, service_role;

-- ───────────────────────── 6. import (actor = auth.uid(), owner/responsabil) ─────────────────────────
CREATE OR REPLACE FUNCTION public.fn_ofertare_source_pack_import(p_pack_id bigint, p_refs text[])
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_actor uuid := auth.uid();
  v_pack public.ofertare_source_pack%ROWTYPE;
  v_nr_anunt text;
  v_ref text;
  v_c jsonb;
  v_doc bigint; v_map text; v_id bigint;
  v_inserate bigint[] := '{}'; v_sarite text[] := '{}'; v_nemapate text[] := '{}'; v_refuzate text[] := '{}';
  v_importabile int; v_importate int; v_stare text; v_hist bigint;
BEGIN
  IF v_actor IS NULL THEN RAISE EXCEPTION 'import: fără sesiune (auth.uid() NULL)'; END IF;
  SELECT * INTO v_pack FROM public.ofertare_source_pack WHERE id = p_pack_id FOR UPDATE;
  IF v_pack.id IS NULL THEN RAISE EXCEPTION 'import: pack inexistent'; END IF;
  IF v_pack.stare = 'respins' THEN RAISE EXCEPTION 'import: pack respins'; END IF;
  -- poarta pe conținut: owner sau responsabilul licitației
  IF NOT EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = v_actor AND pr.is_owner)
     AND NOT EXISTS (SELECT 1 FROM public.ofertare_licitatii l WHERE l.id = v_pack.licitatie_id AND l.responsabil_id = v_actor) THEN
    RAISE EXCEPTION 'import: doar ownerul sau responsabilul licitației';
  END IF;
  -- identitate stabilă pack ↔ licitație (cross-tender blocat)
  SELECT nr_anunt INTO v_nr_anunt FROM public.ofertare_licitatii WHERE id = v_pack.licitatie_id;
  IF (v_pack.pack #>> '{licitatie,licitatie_id}')::bigint IS DISTINCT FROM v_pack.licitatie_id
     OR ((v_pack.pack #>> '{licitatie,nr_anunt}') IS NOT NULL AND (v_pack.pack #>> '{licitatie,nr_anunt}') IS DISTINCT FROM v_nr_anunt) THEN
    RAISE EXCEPTION 'import: pack ≠ licitatie (identitate)';
  END IF;
  IF p_refs IS NULL OR array_length(p_refs, 1) IS NULL THEN RAISE EXCEPTION 'import: niciun ref selectat'; END IF;

  PERFORM set_config('ofertare.import_pack', 'on', true);
  FOREACH v_ref IN ARRAY p_refs LOOP
    SELECT x INTO v_c FROM jsonb_array_elements(v_pack.pack->'cerinte') x WHERE x->>'ref' = v_ref LIMIT 1;
    IF v_c IS NULL THEN v_refuzate := v_refuzate || v_ref; CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.ofertare_cerinte WHERE sursa_pack_id = p_pack_id AND sursa_ref = v_ref) THEN
      v_sarite := v_sarite || v_ref; CONTINUE;
    END IF;
    SELECT document_id, sursa_mapare INTO v_doc, v_map FROM public.fn_ofertare_source_pack_mapeaza_doc(
      v_pack.licitatie_id, v_c#>>'{locator,nume_fisier}', v_c#>>'{locator,seap_cod}',
      (SELECT (dd->>'id')::bigint FROM jsonb_array_elements(COALESCE(v_pack.pack->'documente','[]'::jsonb)) dd
        WHERE dd->>'nume_fisier' = v_c#>>'{locator,nume_fisier}' LIMIT 1));
    IF v_doc IS NULL THEN v_nemapate := v_nemapate || v_ref; CONTINUE; END IF;
    INSERT INTO public.ofertare_cerinte (
      licitatie_id, sursa_document_id, sursa_sectiune, sursa_pagina, pagina_declarata, sursa_pasaj, pasaj_verificat,
      locator_verificat, text_cerinta, tip, lot, document_probant, cand_se_prezinta, incertitudine,
      extras_de_ai, confirmata_de, stare, sursa_pack_id, sursa_ref, sursa_mapare)
    VALUES (
      v_pack.licitatie_id, v_doc, v_c#>>'{locator,sectiune}',
      COALESCE((v_c#>>'{locator,pagina_validata}')::int, (v_c#>>'{locator,pagina}')::int),
      (v_c#>>'{locator,pagina_declarata}')::int,
      v_c#>>'{locator,excerpt}', (v_c#>>'{locator,verificat}') IS NOT NULL,
      v_c#>>'{locator,verificat}',
      v_c->>'text',
      CASE WHEN v_c->>'tip' IN ('eliminatorie','propunere','forma','contractuala') THEN v_c->>'tip' ELSE 'propunere' END,
      v_c->>'lot', v_c->>'document_probant',
      public.fn_ofertare_source_pack_cand(v_c->>'cand_se_prezinta'),
      CASE WHEN v_c->>'incertitudine' IN ('sigur','probabil','neclar') THEN v_c->>'incertitudine' ELSE NULL END,
      true, NULL, 'de_analizat', p_pack_id, v_ref, v_map)
    RETURNING id INTO v_id;
    v_inserate := v_inserate || v_id;
  END LOOP;
  PERFORM set_config('ofertare.import_pack', 'off', true);

  -- istoric append-only: fiecare selecție umană rămâne
  INSERT INTO public.ofertare_source_pack_importuri (pack_id, actor, refs_cerute, inserate, sarite, nemapate, refuzate)
  VALUES (p_pack_id, v_actor, p_refs, v_inserate, v_sarite, v_nemapate, v_refuzate) RETURNING id INTO v_hist;

  -- stare: importat doar când toate cerințele IMPORTABILE (mapabile) sunt în registru
  SELECT count(*) INTO v_importabile FROM public.fn_ofertare_source_pack_preview(p_pack_id) pv WHERE pv.importabil;
  SELECT count(*) INTO v_importate FROM public.ofertare_cerinte WHERE sursa_pack_id = p_pack_id;
  v_stare := CASE WHEN v_importabile > 0 AND v_importate >= v_importabile THEN 'importat' ELSE 'importat_partial' END;
  UPDATE public.ofertare_source_pack SET stare = v_stare, ultim_import_la = now() WHERE id = p_pack_id;

  RETURN jsonb_build_object('import_id', v_hist, 'stare', v_stare, 'actor', v_actor,
    'inserate', to_jsonb(v_inserate), 'sarite', to_jsonb(v_sarite), 'nemapate', to_jsonb(v_nemapate), 'refuzate', to_jsonb(v_refuzate),
    'importabile', v_importabile, 'importate_total', v_importate);
END $fn$;
REVOKE ALL ON FUNCTION public.fn_ofertare_source_pack_import(bigint, text[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_ofertare_source_pack_import(bigint, text[]) TO authenticated;

-- ───────────────────────── 7. nereușite (semnal de acoperire a citirii, niciodată cerințe) ─────────────────────────
CREATE OR REPLACE VIEW public.v_ofertare_source_pack_nereusite WITH (security_invoker = on) AS
SELECT sp.id AS pack_id, sp.licitatie_id, sp.stamp,
       n->>'nume_fisier' AS nume_fisier, n->>'motiv' AS motiv,
       (SELECT count(*) FROM jsonb_array_elements(CASE WHEN jsonb_typeof(n->'pagini')='array' THEN n->'pagini' ELSE '[]'::jsonb END))::int AS nr_pagini,
       n->'pagini' AS pagini, n->>'text_respins' AS text_respins,
       d.document_id, d.sursa_mapare
FROM public.ofertare_source_pack sp
CROSS JOIN LATERAL jsonb_array_elements(COALESCE(sp.pack->'nereusite','[]'::jsonb)) AS n(n)
LEFT JOIN LATERAL public.fn_ofertare_source_pack_mapeaza_doc(sp.licitatie_id, n->>'nume_fisier', NULL, NULL) d ON true;
GRANT SELECT ON public.v_ofertare_source_pack_nereusite TO authenticated, service_role;
