-- Migrarea A (12.09.2026) — schema pentru fluxul „raspuns al autoritatii -> registrul de cerinte",
-- document-first. Inlocuieste fluxul care cerea o clarificare fabricata cu intrebare falsa.

-- ============ 1. SETUL DE RASPUNS ============
-- Un raspuns al autoritatii = un set. Poate fi spart in mai multe documente (pe licitatia 1,
-- raspunsul consolidat de 162 de pagini e spart in 6 parti, documentele 56-61).
CREATE TABLE public.ofertare_raspuns_set (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  licitatie_id bigint NOT NULL REFERENCES public.ofertare_licitatii(id) ON DELETE CASCADE,
  titlu text NOT NULL,
  lot text,
  data_raspuns date,
  stare text NOT NULL DEFAULT 'nou',
  -- Propunerea generata de AI. Omul bifeaza operatii DIN EA, iar aplicarea executa exact ce scrie
  -- aici — niciodata texte primite de la client. Supravietuieste refresh-ului si schimbarii de laptop.
  propunere jsonb,
  propunere_la timestamptz,
  model text,
  cost_usd numeric(10,4),
  -- Cursor: ultimul document analizat. Analiza merge document cu document (tiparul
  -- ofertare-plansa-citeste), pentru ca setul real are 329.056 de caractere.
  analizat_pana_la bigint,
  aplicat_la timestamptz,
  aplicat_de uuid,
  -- Bifa post-depunere inseamna: „confirm actualizarea registrului dupa depunere si imi asum
  -- reverificarea impactului asupra ofertei". NU inseamna ca oferta a fost redepusa.
  aplicat_dupa_depunere boolean NOT NULL DEFAULT false,
  aplicat_motiv text,
  status_licitatie_la_aplicare text,
  -- Retry dupa un commit al carui raspuns s-a pierdut: acelasi key intoarce acelasi rezultat.
  idempotency_key text,
  rezultat jsonb,
  creat_de uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ofertare_raspuns_set_stare_chk
    CHECK (stare IN ('nou','analizat','aplicat_partial','aplicat','fara_efect','anulat')),
  CONSTRAINT ofertare_raspuns_set_titlu_chk CHECK (btrim(titlu) <> ''),
  CONSTRAINT ofertare_raspuns_set_dupa_depunere_chk
    CHECK (NOT aplicat_dupa_depunere OR btrim(coalesce(aplicat_motiv,'')) <> '')
);
COMMENT ON TABLE public.ofertare_raspuns_set IS
  'Un raspuns al autoritatii contractante, eventual spart in mai multe documente. Unitatea de analiza si de aplicare asupra registrului de cerinte.';
COMMENT ON COLUMN public.ofertare_raspuns_set.aplicat_dupa_depunere IS
  'Bifa asumata de om: registrul a fost modificat dupa depunerea ofertei. Nu certifica redepunerea.';

CREATE INDEX ofertare_raspuns_set_licitatie_idx ON public.ofertare_raspuns_set (licitatie_id);
CREATE UNIQUE INDEX ofertare_raspuns_set_idem_uniq
  ON public.ofertare_raspuns_set (idempotency_key) WHERE idempotency_key IS NOT NULL;

-- ============ 2. DOCUMENTELE SETULUI ============
-- ON DELETE RESTRICT pe document: un document care face parte dintr-un set nu se sterge tacit
-- de sub el (DocumenteSection nu are oricum buton de stergere).
CREATE TABLE public.ofertare_raspuns_set_doc (
  set_id bigint NOT NULL REFERENCES public.ofertare_raspuns_set(id) ON DELETE CASCADE,
  document_id bigint NOT NULL REFERENCES public.ofertare_documente_atribuire(id) ON DELETE RESTRICT,
  ordine integer NOT NULL DEFAULT 0,
  PRIMARY KEY (set_id, document_id)
);
CREATE INDEX ofertare_raspuns_set_doc_document_idx ON public.ofertare_raspuns_set_doc (document_id);

-- ============ 3. PROVENIENTA SI ISTORICUL PE CERINTA ============
ALTER TABLE public.ofertare_cerinte
  ADD COLUMN raspuns_set_id bigint REFERENCES public.ofertare_raspuns_set(id) ON DELETE SET NULL,
  ADD COLUMN acoperire_snapshot jsonb;
COMMENT ON COLUMN public.ofertare_cerinte.acoperire_snapshot IS
  'Fotografia acoperirii de pe ACEASTA versiune, scrisa in aceeasi tranzactie INAINTE ca acoperirea sa fie mutata pe versiunea urmatoare. Singurul loc din care se mai poate afla ce dovezi si ce verificari sustineau textul vechi.';

CREATE INDEX ofertare_cerinte_raspuns_set_idx
  ON public.ofertare_cerinte (raspuns_set_id) WHERE raspuns_set_id IS NOT NULL;
-- Acelasi set nu poate introduce de doua ori aceeasi cerinta noua (reluare / dublu-click).
CREATE UNIQUE INDEX ofertare_cerinte_set_text_uniq
  ON public.ofertare_cerinte (raspuns_set_id, md5(btrim(text_cerinta)))
  WHERE raspuns_set_id IS NOT NULL AND versiune = 1;

-- ============ 4. SEMNALUL DE REVERIFICARE PE ACOPERIRE ============
-- Acoperirea se MUTA pe versiunea noua (UPDATE cerinta_id), nu se copiaza cu verificat_pe_scan=false:
-- indexul unic partial ofertare_acoperire_cerinta_unic_nevalidat permite UN singur rand nevalidat
-- per cerinta, iar cerintele 1061 (3 randuri) si 1069 (2 randuri) ar fi anulat toata tranzactia.
-- Semnalul „textul cerintei s-a schimbat, revezi dovada" traieste aici, nu in verificat_pe_scan.
ALTER TABLE public.ofertare_acoperire
  ADD COLUMN reverificare_ceruta boolean NOT NULL DEFAULT false,
  ADD COLUMN reverificare_motiv text;
CREATE INDEX ofertare_acoperire_reverificare_idx
  ON public.ofertare_acoperire (cerinta_id) WHERE reverificare_ceruta;

-- ============ 5. DREPTURI ============
-- Privilegiile implicite din Supabase dau anon DML complet pe orice tabel nou (verificat pe
-- ofertare_acoperire). Pe tabelele astea se revoca explicit.
CREATE OR REPLACE FUNCTION public.fn_are_acces_ofertare(p_uid uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
  SELECT p_uid IS NOT NULL AND (
    EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = p_uid AND pr.is_owner)
    OR EXISTS (SELECT 1 FROM public.user_module_access uma
               WHERE uma.profile_id = p_uid AND uma.module = 'ofertare')
  );
$fn$;
REVOKE EXECUTE ON FUNCTION public.fn_are_acces_ofertare(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_are_acces_ofertare(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_are_acces_ofertare(uuid) TO authenticated, service_role;

ALTER TABLE public.ofertare_raspuns_set ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ofertare_raspuns_set_doc ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.ofertare_raspuns_set FROM PUBLIC;
REVOKE ALL ON public.ofertare_raspuns_set FROM anon;
REVOKE ALL ON public.ofertare_raspuns_set_doc FROM PUBLIC;
REVOKE ALL ON public.ofertare_raspuns_set_doc FROM anon;
GRANT SELECT ON public.ofertare_raspuns_set TO authenticated;
GRANT SELECT ON public.ofertare_raspuns_set_doc TO authenticated;
GRANT ALL ON public.ofertare_raspuns_set TO service_role;
GRANT ALL ON public.ofertare_raspuns_set_doc TO service_role;

-- Citire: doar cine are efectiv modulul Ofertare. Scrierile trec exclusiv prin edge/RPC cu service_role.
CREATE POLICY ofertare_raspuns_set_citire ON public.ofertare_raspuns_set
  FOR SELECT TO authenticated
  USING (public.fn_are_acces_ofertare(auth.uid()));
CREATE POLICY ofertare_raspuns_set_doc_citire ON public.ofertare_raspuns_set_doc
  FOR SELECT TO authenticated
  USING (public.fn_are_acces_ofertare(auth.uid()));
