-- [CTC] F1 — Cărți Tehnice ale Construcției (spec: claude_docs.spec_modul_ctc_carti_tehnice, claude_context #653).
-- Decizii Răzvan 30.09.2026: Q1 A+C (schelet Transgaz generic acum, pozițiile reale extrase ulterior din cărțile
-- de pe NAS) · Q2 B (O SINGURĂ carte pe proiect) · Q3 B (poziție atașabilă din arhiva comenzilor furnizor, prin
-- referință, fără re-upload) · Q4 A (bucket ctc-documente, 50 MB/fișier, doar PDF — imaginile se convertesc
-- client-side, decizia „TOTUL PDF").
-- Acces: profiles.can_access_ctc OR profiles.is_owner (ca în spec). Ștergerea unei cărți: doar owner.
-- Tabela veche ctc_documente (goală, legată de comenzi) NU se atinge.
-- Obiecte noi: 4 tabele + 1 view (security_invoker) + bucket + policies. Fără funcții, fără edge functions.

-- ─── 1. Template-uri per beneficiar ─────────────────────────────
CREATE TABLE public.ctc_templates (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiar_nume text NOT NULL,
  denumire        text NOT NULL,
  activ           boolean NOT NULL DEFAULT true,
  observatii      text,
  created_by      uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.ctc_templates IS '[CTC] Template carte tehnică per beneficiar (Transgaz, Distrigaz, Delgaz…). Checklist-ul stă în ctc_template_pozitii.';

CREATE TABLE public.ctc_template_pozitii (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id       bigint NOT NULL REFERENCES public.ctc_templates(id) ON DELETE CASCADE,
  categorie         text NOT NULL,
  denumire_document text NOT NULL,
  ordine            int  NOT NULL,
  obligatoriu       boolean NOT NULL DEFAULT true,
  observatii        text,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ctc_template_pozitii_tpl_idx ON public.ctc_template_pozitii (template_id, ordine);
COMMENT ON TABLE public.ctc_template_pozitii IS '[CTC] Pozițiile (documentele cerute) ale unui template, în ordinea din borderou.';

-- ─── 2. Cărțile ─────────────────────────────────────────────────
CREATE TABLE public.ctc_carti (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proiect_id           bigint REFERENCES public.executie_proiecte(id) ON DELETE SET NULL,
  contract_id          bigint REFERENCES public.contracte_terti(id)   ON DELETE SET NULL,
  template_id          bigint REFERENCES public.ctc_templates(id)     ON DELETE SET NULL,
  beneficiar_nume      text,
  denumire_obiectiv    text NOT NULL,
  numar_contract       text,
  data_contract        date,
  localitate           text,
  judet                text,
  status               text NOT NULL DEFAULT 'in_lucru' CHECK (status IN ('in_lucru','completa','predata')),
  borderou_path        text,
  borderou_generat_at  timestamptz,
  pdf_final_path       text,          -- F2 (PDF unificat, Edge Function)
  pdf_final_generat_at timestamptz,   -- F2
  predat_la            date,
  predat_catre         text,
  pv_predare_path      text,
  observatii           text,
  created_by           uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ctc_carti_proiect_unic UNIQUE (proiect_id)   -- Q2 B: o singură carte pe proiect (NULL = lucrare fără proiect în Execuție)
);
COMMENT ON TABLE public.ctc_carti IS '[CTC] Cartea Tehnică a Construcției: dosarul de conformitate predat beneficiarului la recepție. 1 carte / proiect.';

-- ─── 3. Documentele unei cărți (checklist-ul concret) ───────────
CREATE TABLE public.ctc_documente_carte (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carte_id            bigint NOT NULL REFERENCES public.ctc_carti(id) ON DELETE CASCADE,
  template_pozitie_id bigint REFERENCES public.ctc_template_pozitii(id) ON DELETE SET NULL,
  categorie           text NOT NULL,
  denumire_document   text NOT NULL,
  nr_pozitie          int,             -- numărul din borderou (se recalculează la generare)
  ordine              int NOT NULL,
  obligatoriu         boolean NOT NULL DEFAULT true,
  status              text NOT NULL DEFAULT 'lipsa' CHECK (status IN ('lipsa','incarcat','verificat','na')),
  -- fișierul: fie urcat în ctc-documente, fie referință la un document din arhiva comenzilor (Q3 B)
  sursa               text NOT NULL DEFAULT 'upload' CHECK (sursa IN ('upload','arhiva_comenzi')),
  fisier_bucket       text NOT NULL DEFAULT 'ctc-documente' CHECK (fisier_bucket IN ('ctc-documente','comenzi-furnizor')),
  fisier_path         text,
  fisier_nume         text,
  fisier_size_bytes   bigint,
  cfd_id              bigint REFERENCES public.comenzi_furnizor_documente(id) ON DELETE SET NULL,
  nr_pagini           int CHECK (nr_pagini IS NULL OR nr_pagini > 0),
  nr_pagina_start     int,
  nr_pagina_end       int,
  observatii          text,
  uploadat_de         uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  uploadat_la         timestamptz,
  verificat_de        uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  verificat_la        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ctc_doc_sursa_coerenta CHECK (
    (sursa = 'upload' AND fisier_bucket = 'ctc-documente')
    OR (sursa = 'arhiva_comenzi' AND fisier_bucket = 'comenzi-furnizor')
  )
);
CREATE INDEX ctc_documente_carte_carte_idx ON public.ctc_documente_carte (carte_id, ordine);
CREATE INDEX ctc_documente_carte_cfd_idx   ON public.ctc_documente_carte (cfd_id) WHERE cfd_id IS NOT NULL;
COMMENT ON TABLE public.ctc_documente_carte IS '[CTC] Pozițiile concrete ale unei cărți (copiate din template la creare, editabile). Fișier propriu sau referință la comenzi_furnizor_documente.';

-- ─── 4. updated_at ──────────────────────────────────────────────
CREATE TRIGGER ctc_templates_updated_at       BEFORE UPDATE ON public.ctc_templates       FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER ctc_carti_updated_at           BEFORE UPDATE ON public.ctc_carti           FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER ctc_documente_carte_updated_at BEFORE UPDATE ON public.ctc_documente_carte FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─── 5. RLS + GRANT ─────────────────────────────────────────────
ALTER TABLE public.ctc_templates        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ctc_template_pozitii ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ctc_carti            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ctc_documente_carte  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.ctc_templates, public.ctc_template_pozitii, public.ctc_carti, public.ctc_documente_carte FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ctc_templates, public.ctc_template_pozitii, public.ctc_carti, public.ctc_documente_carte TO authenticated;
GRANT ALL ON public.ctc_templates, public.ctc_template_pozitii, public.ctc_carti, public.ctc_documente_carte TO service_role;

-- Acces CTC = can_access_ctc OR is_owner. Ștergerea unei cărți întregi = doar owner.
DO $$
DECLARE t text;
  acces constant text := '(auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)))';
  owner constant text := '(auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.is_owner))';
BEGIN
  FOREACH t IN ARRAY ARRAY['ctc_templates','ctc_template_pozitii','ctc_carti','ctc_documente_carte'] LOOP
    EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING %s', t||'_select', t, acces);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK %s', t||'_insert', t, acces);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING %s WITH CHECK %s', t||'_update', t, acces, acces);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING %s', t||'_delete', t,
                   CASE WHEN t = 'ctc_carti' THEN owner ELSE acces END);
  END LOOP;
END $$;

-- ─── 6. View progres (checklist „47/93") ────────────────────────
CREATE VIEW public.v_ctc_carti_progres WITH (security_invoker = on) AS
SELECT c.id AS carte_id,
       count(d.id)                                                          AS total_pozitii,
       count(d.id) FILTER (WHERE d.status <> 'na')                           AS pozitii_aplicabile,
       count(d.id) FILTER (WHERE d.status IN ('incarcat','verificat'))       AS pozitii_incarcate,
       count(d.id) FILTER (WHERE d.status = 'verificat')                     AS pozitii_verificate,
       count(d.id) FILTER (WHERE d.status = 'lipsa' AND d.obligatoriu)       AS obligatorii_lipsa,
       coalesce(sum(d.nr_pagini) FILTER (WHERE d.status IN ('incarcat','verificat')), 0) AS total_pagini
FROM public.ctc_carti c
LEFT JOIN public.ctc_documente_carte d ON d.carte_id = c.id
GROUP BY c.id;
REVOKE ALL ON public.v_ctc_carti_progres FROM anon;
GRANT SELECT ON public.v_ctc_carti_progres TO authenticated, service_role;

-- ─── 7. Bucket ctc-documente (privat, 50 MB, doar PDF) ──────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('ctc-documente', 'ctc-documente', false, 52428800, ARRAY['application/pdf'])
ON CONFLICT (id) DO NOTHING;

CREATE POLICY ctc_storage_select ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));
CREATE POLICY ctc_storage_insert ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));
CREATE POLICY ctc_storage_update ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));
CREATE POLICY ctc_storage_delete ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'ctc-documente' AND auth.uid() IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_owner OR p.can_access_ctc)));

-- ─── 8. Seed: template Transgaz — SCHELET GENERIC (Q1 C) ────────
-- Structura pe categorii din spec (borderou BUSAG). Pozițiile reale (93+) se completează ulterior (Q1 A)
-- din cărțile de pe NAS (TIGVENI, Râul Doamnei) — prin UI sau o migrare separată, cu preview.
WITH t AS (
  INSERT INTO public.ctc_templates (beneficiar_nume, denumire, observatii, created_by)
  VALUES ('Transgaz', 'Transgaz — conductă transport (schelet generic)',
          'Schelet din spec (categorii BUSAG). De completat cu pozițiile reale din cărțile TIGVENI / Râul Doamnei.', NULL)
  RETURNING id
)
INSERT INTO public.ctc_template_pozitii (template_id, categorie, denumire_document, ordine, obligatoriu, observatii)
SELECT t.id, v.categorie, v.denumire, v.ordine, v.obligatoriu, v.obs
FROM t, (VALUES
  ('Autorizații & avize',        'Autorizație de construire',                                         10, true,  NULL),
  ('Autorizații & avize',        'Autorizație ANRE (ET / EPI)',                                        20, true,  NULL),
  ('Autorizații & avize',        'Comunicare începere lucrări către ISC',                              30, true,  NULL),
  ('Autorizații & avize',        'Răspuns / confirmare ISC',                                           40, false, NULL),
  ('Autorizații & avize',        'Ordin de începere',                                                  50, true,  NULL),
  ('Autorizații & avize',        'PV predare-primire amplasament',                                     60, true,  NULL),
  ('Decizii numire personal',    'Decizie numire Responsabil Tehnic cu Execuția (RTE)',                110, true,  NULL),
  ('Decizii numire personal',    'Decizie numire Responsabil Tehnic cu Sudura (RTS) + atestat ISCIR',  120, true,  NULL),
  ('Decizii numire personal',    'Decizie numire manager proiect / șef de șantier',                   130, true,  NULL),
  ('Decizii numire personal',    'Decizie numire responsabil CTC',                                    140, true,  NULL),
  ('Decizii numire personal',    'Tabel sudori autorizați + autorizații',                              150, true,  NULL),
  ('Program control calitate',   'PCCVI (program de control al calității, verificări și încercări)',  210, true,  NULL),
  ('Certificate materiale',      'Țeavă — declarație conformitate + certificat inspecție + packing list', 310, true,  NULL),
  ('Certificate materiale',      'Curbe R=5xDn — declarație conformitate + certificat inspecție',     320, true,  NULL),
  ('Certificate materiale',      'Izolație suduri (manșoane termocontractabile) — certificate',        330, true,  NULL),
  ('Certificate materiale',      'Benzi PE — certificate',                                             340, false, NULL),
  ('Certificate materiale',      'Electrozi / material de adaos — certificate',                        350, true,  NULL),
  ('Certificate materiale',      'Bicomponent A+B — certificate',                                      360, false, NULL),
  ('Certificate materiale',      'Alte materiale — certificate',                                       370, false, NULL),
  ('PVRC — recepție calitativă', 'PV recepție calitativă materiale',                                  410, true,  'Câte unul per material/operație'),
  ('PVLA — lucrări ascunse',     'PVLA săpătură șanț',                                                 510, true,  'Separat mal stâng / mal drept, dacă e cazul'),
  ('PVLA — lucrări ascunse',     'PVLA pat de pământ mărunțit',                                        520, true,  NULL),
  ('PVLA — lucrări ascunse',     'PVLA montaj țeavă în șanț',                                          530, true,  NULL),
  ('PVLA — lucrări ascunse',     'PVLA curățare suprafețe metalice',                                   540, true,  NULL),
  ('PVLA — lucrări ascunse',     'PVLA izolare suduri',                                                550, true,  NULL),
  ('PVLA — lucrări ascunse',     'PVLA astupare șanț',                                                 560, true,  NULL),
  ('Sudură',                     'WPQR',                                                               610, true,  NULL),
  ('Sudură',                     'WPS',                                                                620, true,  NULL),
  ('Sudură',                     'Tabele execuție suduri (per tronson)',                               630, true,  NULL),
  ('Sudură',                     'Buletine examinare vizuală',                                         640, true,  NULL),
  ('Sudură',                     'Buletine control nedistructiv (RT / UT)',                            650, true,  NULL),
  ('Probe presiune',             'Program faze determinante',                                          710, true,  NULL),
  ('Probe presiune',             'PV probă de rezistență',                                             720, true,  NULL),
  ('Probe presiune',             'PV probă de etanșeitate',                                            730, true,  NULL),
  ('Probe presiune',             'Diagrame înregistrare presiune',                                     740, true,  NULL),
  ('Probe presiune',             'PV pistonare / curățare',                                            750, false, NULL),
  ('As-Built',                   'Plan as-built / traseu executat',                                    810, true,  NULL),
  ('As-Built',                   'Schemă izometrică',                                                  820, true,  NULL),
  ('As-Built',                   'Profil longitudinal',                                                830, true,  NULL),
  ('As-Built',                   'FOD / foraj executat',                                               840, false, 'Doar la subtraversări prin foraj'),
  ('Rapoarte & buletine',        'Verificare izolație (după tragere / înainte de astupare)',           910, true,  NULL),
  ('Rapoarte & buletine',        'Buletine de măsurare',                                               920, false, NULL),
  ('Calibrări AMC',              'Certificate calibrare aparate (manometre, detector izolație etc.)',  1010, true, NULL)
) AS v(categorie, denumire, ordine, obligatoriu, obs);
